export type ZodiacSign = { slug:string; name:string; glyph:string; element:string; modality:string; ruler:string; dates:string; keywords:string[]; summary:string; strength:string; challenge:string };
export type Planet = { slug:string; name:string; glyph:string; astronomy:string; astrology:string; keywords:string[]; retrograde?:boolean };
export type MoonPhase = { slug:string; name:string; glyph:string; min:number; max:number; astronomy:string; reflection:string };

export const ZODIAC_SIGNS: ZodiacSign[] = [
{slug:"aries",name:"Aries",glyph:"♈",element:"Fire",modality:"Cardinal",ruler:"Mars",dates:"approximately March 21–April 19",keywords:["initiative","courage","directness"],summary:"Aries is the first tropical zodiac sign and is traditionally associated with initiation, decisiveness, and direct forward motion.",strength:"Acts quickly when momentum matters and tends to prefer experience over excessive preparation.",challenge:"Speed can become impatience; strong initiative works best when paired with enough listening and follow-through."},
{slug:"taurus",name:"Taurus",glyph:"♉",element:"Earth",modality:"Fixed",ruler:"Venus",dates:"approximately April 20–May 20",keywords:["stability","sensuality","persistence"],summary:"Taurus is a fixed earth sign traditionally associated with continuity, material steadiness, patience, and sensory appreciation.",strength:"Builds slowly and reliably, often valuing durability, comfort, and tangible results.",challenge:"Consistency can harden into resistance when circumstances genuinely require adaptation."},
{slug:"gemini",name:"Gemini",glyph:"♊",element:"Air",modality:"Mutable",ruler:"Mercury",dates:"approximately May 21–June 20",keywords:["curiosity","language","adaptability"],summary:"Gemini is a mutable air sign traditionally associated with exchange, information, movement, and intellectual variety.",strength:"Connects ideas and people quickly, asking questions and translating between viewpoints.",challenge:"Variety can scatter attention unless curiosity is given a useful structure."},
{slug:"cancer",name:"Cancer",glyph:"♋",element:"Water",modality:"Cardinal",ruler:"Moon",dates:"approximately June 21–July 22",keywords:["care","memory","belonging"],summary:"Cancer is a cardinal water sign traditionally associated with protection, belonging, emotional memory, and the creation of safe foundations.",strength:"Notices emotional undercurrents and often invests deeply in people, places, and traditions that feel meaningful.",challenge:"Protectiveness can become withdrawal or over-identification with the past."},
{slug:"leo",name:"Leo",glyph:"♌",element:"Fire",modality:"Fixed",ruler:"Sun",dates:"approximately July 23–August 22",keywords:["expression","warmth","creative pride"],summary:"Leo is a fixed fire sign traditionally associated with creative visibility, generosity, performance, and wholehearted self-expression.",strength:"Brings warmth and conviction to projects and relationships, especially when there is room to create or lead.",challenge:"The wish to be appreciated can become rigidity or unnecessary performance when validation becomes the goal."},
{slug:"virgo",name:"Virgo",glyph:"♍",element:"Earth",modality:"Mutable",ruler:"Mercury",dates:"approximately August 23–September 22",keywords:["discernment","craft","service"],summary:"Virgo is a mutable earth sign traditionally associated with analysis, refinement, practical skill, and attention to what can be improved.",strength:"Finds useful distinctions, repairs weak systems, and often turns vague intentions into workable routines.",challenge:"Discernment can become chronic criticism when nothing is allowed to be good enough."},
{slug:"libra",name:"Libra",glyph:"♎",element:"Air",modality:"Cardinal",ruler:"Venus",dates:"approximately September 23–October 22",keywords:["balance","relationship","judgment"],summary:"Libra is a cardinal air sign traditionally associated with relationship, comparison, fairness, aesthetics, and negotiated balance.",strength:"Can see competing perspectives and create social or aesthetic coherence between them.",challenge:"Keeping every option open can delay necessary decisions or hide personal preference."},
{slug:"scorpio",name:"Scorpio",glyph:"♏",element:"Water",modality:"Fixed",ruler:"Mars / Pluto",dates:"approximately October 23–November 21",keywords:["depth","intensity","transformation"],summary:"Scorpio is a fixed water sign traditionally associated with emotional depth, secrecy, resilience, power, and processes of transformation.",strength:"Stays with difficult material long enough to understand what is actually driving it.",challenge:"Intensity can become control, suspicion, or difficulty releasing a position after it has stopped serving."},
{slug:"sagittarius",name:"Sagittarius",glyph:"♐",element:"Fire",modality:"Mutable",ruler:"Jupiter",dates:"approximately November 22–December 21",keywords:["exploration","belief","perspective"],summary:"Sagittarius is a mutable fire sign traditionally associated with exploration, philosophy, candor, and the search for a larger frame of meaning.",strength:"Expands horizons through study, travel, humor, experimentation, and willingness to think beyond immediate circumstances.",challenge:"Big-picture confidence can skip important details or become certainty before evidence warrants it."},
{slug:"capricorn",name:"Capricorn",glyph:"♑",element:"Earth",modality:"Cardinal",ruler:"Saturn",dates:"approximately December 22–January 19",keywords:["structure","ambition","responsibility"],summary:"Capricorn is a cardinal earth sign traditionally associated with structure, long-term effort, accountability, and practical ambition.",strength:"Works patiently toward durable outcomes and tends to respect competence earned through repetition and responsibility.",challenge:"Duty can become over-control or a tendency to measure worth only through achievement."},
{slug:"aquarius",name:"Aquarius",glyph:"♒",element:"Air",modality:"Fixed",ruler:"Saturn / Uranus",dates:"approximately January 20–February 18",keywords:["systems","independence","future"],summary:"Aquarius is a fixed air sign traditionally associated with systems thinking, independence, social ideals, and unconventional perspectives.",strength:"Can detach from convention enough to see alternative structures, communities, or technologies.",challenge:"Intellectual independence can turn into contrarian distance or neglect of immediate emotional realities."},
{slug:"pisces",name:"Pisces",glyph:"♓",element:"Water",modality:"Mutable",ruler:"Jupiter / Neptune",dates:"approximately February 19–March 20",keywords:["imagination","empathy","permeability"],summary:"Pisces is a mutable water sign traditionally associated with imagination, compassion, porous boundaries, and symbolic or artistic sensitivity.",strength:"Moves easily between perspectives and can translate subtle emotional material into art, care, or intuition.",challenge:"Permeability needs boundaries; otherwise empathy and imagination can blur into avoidance or confusion."}
];

export const PLANETS: Planet[] = [
{slug:"sun",name:"Sun",glyph:"☉",astronomy:"The Sun is the star at the center of the Solar System; Earth orbits it once each tropical year.",astrology:"In Western astrology, the Sun symbolizes identity, vitality, purpose, and the organizing center of self-expression.",keywords:["identity","vitality","purpose"]},
{slug:"moon",name:"Moon",glyph:"☽",astronomy:"The Moon is Earth's natural satellite. Its synodic phase cycle averages about 29.53 days.",astrology:"Astrologically, the Moon is associated with emotional habit, instinct, memory, care, and felt security.",keywords:["emotion","habit","security"]},
{slug:"mercury",name:"Mercury",glyph:"☿",astronomy:"Mercury is the innermost planet and completes an orbit around the Sun in about 88 days.",astrology:"Mercury symbolizes communication, language, categorization, movement, and the style of thinking.",keywords:["communication","thought","exchange"],retrograde:true},
{slug:"venus",name:"Venus",glyph:"♀",astronomy:"Venus is the second planet from the Sun and appears from Earth as a bright morning or evening object.",astrology:"Venus symbolizes attraction, relationship style, aesthetics, pleasure, values, and patterns of reciprocity.",keywords:["attraction","values","relationship"],retrograde:true},
{slug:"mars",name:"Mars",glyph:"♂",astronomy:"Mars is the fourth planet from the Sun, with an orbital period of about 687 Earth days.",astrology:"Mars symbolizes drive, assertion, conflict style, pursuit, courage, and how effort is mobilized.",keywords:["drive","assertion","action"],retrograde:true},
{slug:"jupiter",name:"Jupiter",glyph:"♃",astronomy:"Jupiter is the Solar System's largest planet and takes about 11.86 years to orbit the Sun.",astrology:"Jupiter symbolizes expansion, opportunity, belief, confidence, education, and the search for a wider horizon.",keywords:["expansion","belief","opportunity"],retrograde:true},
{slug:"saturn",name:"Saturn",glyph:"♄",astronomy:"Saturn is a gas giant with a prominent ring system and an orbital period of about 29.5 years.",astrology:"Saturn symbolizes limits, responsibility, time, structure, accountability, and long-term mastery.",keywords:["structure","limits","mastery"],retrograde:true},
{slug:"uranus",name:"Uranus",glyph:"♅",astronomy:"Uranus is an ice giant with an orbital period of about 84 years and an unusually tilted rotation axis.",astrology:"Modern astrology associates Uranus with disruption, innovation, independence, shocks, and unconventional change.",keywords:["innovation","disruption","freedom"],retrograde:true},
{slug:"neptune",name:"Neptune",glyph:"♆",astronomy:"Neptune is the outermost major planet, taking about 165 years to orbit the Sun.",astrology:"Modern astrology associates Neptune with imagination, idealization, permeability, spirituality, and ambiguity.",keywords:["imagination","idealization","ambiguity"],retrograde:true},
{slug:"pluto",name:"Pluto",glyph:"♇",astronomy:"Pluto is a dwarf planet in the Kuiper belt with an orbital period of about 248 years.",astrology:"Modern astrology associates Pluto with power, compulsion, deep transformation, loss, and regeneration.",keywords:["power","transformation","regeneration"],retrograde:true}
];

export const MOON_PHASES: MoonPhase[] = [
{slug:"new-moon",name:"New Moon",glyph:"🌑",min:0,max:1.84566,astronomy:"The Moon is near conjunction with the Sun, so its sunlit hemisphere is mostly turned away from Earth.",reflection:"Symbolically, modern astrology often treats the New Moon as a reset point for intention and beginnings."},
{slug:"waxing-crescent",name:"Waxing Crescent",glyph:"🌒",min:1.84566,max:5.53699,astronomy:"A growing crescent becomes visible after new moon as the Moon moves eastward from the Sun in the sky.",reflection:"Often used as a symbolic period for beginning to act on an intention and building early momentum."},
{slug:"first-quarter",name:"First Quarter",glyph:"🌓",min:5.53699,max:9.22831,astronomy:"Roughly half of the visible lunar disk is illuminated while the Moon is about 90 degrees east of the Sun.",reflection:"Often framed symbolically as a point of action, friction, decision, and adjustment."},
{slug:"waxing-gibbous",name:"Waxing Gibbous",glyph:"🌔",min:9.22831,max:12.91963,astronomy:"More than half of the visible disk is illuminated and the illuminated fraction continues increasing toward full moon.",reflection:"Modern symbolic practice often treats this phase as refinement, preparation, and sustained effort."},
{slug:"full-moon",name:"Full Moon",glyph:"🌕",min:12.91963,max:16.61096,astronomy:"The Moon is near opposition to the Sun, with its Earth-facing hemisphere largely illuminated.",reflection:"Often treated symbolically as culmination, visibility, heightened awareness, or a point of release."},
{slug:"waning-gibbous",name:"Waning Gibbous",glyph:"🌖",min:16.61096,max:20.30228,astronomy:"The visible illuminated fraction decreases after full moon while more than half the lunar disk remains lit.",reflection:"Modern symbolic practice often emphasizes integration, sharing, evaluation, and letting a result settle."},
{slug:"last-quarter",name:"Last Quarter",glyph:"🌗",min:20.30228,max:23.99361,astronomy:"About half of the visible lunar disk is illuminated while the Moon is roughly 90 degrees west of the Sun.",reflection:"Often framed as a symbolic checkpoint for revision, release, and deliberate course correction."},
{slug:"waning-crescent",name:"Waning Crescent",glyph:"🌘",min:23.99361,max:29.53058867,astronomy:"Only a shrinking crescent remains visible before the Moon returns to conjunction with the Sun.",reflection:"Often treated symbolically as a quieter period for rest, closure, reflection, and clearing space."}
];

export const RETROGRADE_PLANETS = PLANETS.filter((item) => item.retrograde && ["mercury","venus","mars","jupiter","saturn"].includes(item.slug));

export function zodiacBySlug(slug:string){ return ZODIAC_SIGNS.find((item)=>item.slug===slug); }
export function planetBySlug(slug:string){ return PLANETS.find((item)=>item.slug===slug); }
export function phaseBySlug(slug:string){ return MOON_PHASES.find((item)=>item.slug===slug); }
