import { MOON_PHASES, PLANETS, RETROGRADE_PLANETS, ZODIAC_SIGNS, phaseBySlug, planetBySlug, zodiacBySlug } from "./astrology-data.ts";

const HOST = "https://oraclemirror.com";
const LASTMOD = "2026-09-07";

function esc(value:string){return value.replace(/[&<>'"]/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]||c));}
function safeJson(value:unknown){return JSON.stringify(value).replace(/</g,"\\u003c");}
function layout(o:{title:string;description:string;canonical:string;body:string;jsonLd?:unknown[]}){
  const ld=(o.jsonLd||[]).map((x)=>`<script type="application/ld+json">${safeJson(x)}</script>`).join("\n");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(o.title)}</title><meta name="description" content="${esc(o.description)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${o.canonical}"><link rel="icon" type="image/svg+xml" href="/favicon.svg"><meta name="theme-color" content="#07050d"><meta property="og:type" content="website"><meta property="og:site_name" content="Oracle Mirror"><meta property="og:title" content="${esc(o.title)}"><meta property="og:description" content="${esc(o.description)}"><meta property="og:url" content="${o.canonical}"><meta property="og:image" content="${HOST}/og-image.png"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/astrology.css">${ld}</head><body class="astrology-body"><header class="astrology-header"><nav class="astrology-nav" aria-label="Astrology navigation"><a class="astrology-brand" href="/">☼ Oracle Mirror</a><div><a href="/astrology">Astrology</a><a href="/astrology/moon">Moon</a><a href="/astrology/zodiac">Zodiac</a><a href="/astrology/planets">Planets</a><a href="/birth-chart">Birth Chart Tool</a></div></nav></header>${o.body}<footer class="astrology-footer"><a href="/">Oracle Mirror</a><span>·</span><a href="/privacy-policy">Privacy</a><span>·</span><a href="/contact">Contact</a><p>Astronomy facts and symbolic astrology are labelled separately. Astrology is an interpretive tradition, not a scientific prediction method.</p></footer></body></html>`;
}

function cards<T>(items:T[],render:(item:T)=>string){return items.map(render).join("");}
export function isAstrologyRoute(path:string){return path==="/astrology"||path==="/astrology/"||/^\/astrology\/(?:moon(?:\/phases(?:\/[a-z0-9-]+)?)?|zodiac(?:\/[a-z0-9-]+)?|planets(?:\/[a-z0-9-]+)?|retrogrades(?:\/[a-z0-9-]+)?|transits|birth-chart)\/?$/.test(path);}

export function astrologySitemapUrls(){return [
  "/astrology","/astrology/moon","/astrology/moon/phases",...MOON_PHASES.map(x=>`/astrology/moon/phases/${x.slug}`),
  "/astrology/zodiac",...ZODIAC_SIGNS.map(x=>`/astrology/zodiac/${x.slug}`),
  "/astrology/planets",...PLANETS.map(x=>`/astrology/planets/${x.slug}`),
  "/astrology/retrogrades",...RETROGRADE_PLANETS.map(x=>`/astrology/retrogrades/${x.slug}`),
  "/astrology/transits","/astrology/birth-chart"
];}

export function augmentSitemapWithAstrology(xml:string){if(!xml.includes("</urlset>")||xml.includes(`${HOST}/astrology</loc>`))return xml;const add=astrologySitemapUrls().map(path=>`  <url><loc>${HOST}${path}</loc><lastmod>${LASTMOD}</lastmod><changefreq>${path==="/astrology/moon"?"weekly":"yearly"}</changefreq><priority>${["/astrology","/astrology/moon","/astrology/zodiac","/astrology/planets"].includes(path)?"0.8":"0.55"}</priority></url>`).join("\n");return xml.replace("</urlset>",`${add}\n</urlset>`);}
export function augmentLlmsWithAstrology(text:string){if(text.includes("## Astrology & Lunar Guides"))return text;return `${text.trimEnd()}\n\n## Astrology & Lunar Guides\n- ${HOST}/astrology — astrology reference hub separating astronomical facts from symbolic interpretation.\n- ${HOST}/astrology/moon — local approximate Moon phase calculator and 15-day lunar window.\n- ${HOST}/astrology/moon/phases — eight lunar phase guides.\n- ${HOST}/astrology/zodiac — twelve tropical zodiac sign guides.\n- ${HOST}/astrology/planets — astronomical facts and traditional astrological symbolism for ten bodies.\n- ${HOST}/astrology/retrogrades — explanation of apparent retrograde motion plus symbolic astrology guides.\n- ${HOST}/astrology/transits — educational guide to what astrologers mean by transits.\n- ${HOST}/astrology/birth-chart — educational guide to signs, houses, planets, aspects, and why precise birth time matters.\n`;}
export function injectAstrologyDiscovery(html:string){if(!html||html.includes('href="/astrology"'))return html;let next=html;next=next.replace(/(<a href="\/western-zodiac" class="dropdown-item"[^>]*>.*?<\/a>)/,'$1\n              <a href="/astrology" class="dropdown-item">☾ Astrology & Moon</a>');next=next.replace("advanced numerology, and AI Soulmate Vision","advanced numerology, astrology and lunar guides, and AI Soulmate Vision");return next;}

export function renderAstrologyHub(){const title="Astrology Guide — Moon, Zodiac, Planets & Birth Charts | Oracle Mirror";const description="Explore Moon phases, the 12 zodiac signs, planetary symbolism, retrogrades, transits, and birth-chart basics with astronomy and astrology clearly separated.";const body=`<main class="astrology-main"><section class="astrology-hero"><p class="astrology-kicker">Astronomy facts · symbolic astrology</p><div class="astrology-glyphs">☉ ☽ ☿ ♀ ♂ ♃ ♄</div><h1>Astrology & Lunar Guide</h1><p>Use Oracle Mirror as a map of the concepts astrologers talk about—without confusing symbolic interpretation with astronomy. The Moon calculator uses a transparent approximate lunar-cycle model; zodiac, planets, retrogrades, transits, and birth-chart pages explain the interpretive tradition around those observations.</p></section><section class="astrology-feature-grid"><a href="/astrology/moon"><strong>☽ Moon Calendar</strong><span>Approximate phase, illumination and 15-day window</span></a><a href="/astrology/zodiac"><strong>♈ 12 Zodiac Signs</strong><span>Elements, modalities, rulers and sign meanings</span></a><a href="/astrology/planets"><strong>☉ Planetary Symbols</strong><span>Astronomy facts beside traditional meanings</span></a><a href="/astrology/retrogrades"><strong>℞ Retrogrades</strong><span>Real apparent motion versus symbolic interpretation</span></a><a href="/astrology/transits"><strong>✦ Transits</strong><span>What a transit is and how astrologers read one</span></a><a href="/astrology/birth-chart"><strong>◎ Birth Chart Basics</strong><span>Planets, signs, houses, aspects and birth-time precision</span></a></section><section class="astrology-note"><h2>Two different layers</h2><p><strong>Astronomy</strong> describes physical positions, cycles and apparent motions of celestial bodies. <strong>Astrology</strong> assigns symbolic meanings to those observations. Oracle Mirror keeps the two layers labelled instead of presenting symbolic claims as measured astronomical effects.</p><div class="astrology-actions"><a class="btn-gold" href="/birth-chart">Open Birth Chart Tool</a><a class="btn-ghost" href="/western-zodiac">Classic Zodiac Reading</a></div></section></main>`;const ld=[{"@context":"https://schema.org","@type":"CollectionPage",name:"Oracle Mirror Astrology & Lunar Guide",url:`${HOST}/astrology`,description},{"@context":"https://schema.org","@type":"ItemList",name:"Astrology guide sections",numberOfItems:6,itemListElement:["moon","zodiac","planets","retrogrades","transits","birth-chart"].map((x,i)=>({"@type":"ListItem",position:i+1,url:`${HOST}/astrology/${x}`}))}];return html(layout({title,description,canonical:`${HOST}/astrology`,body,jsonLd:ld}));}

export function renderMoonPage(){const title="Moon Phase Calculator & 15-Day Lunar Calendar | Oracle Mirror";const description="Choose a date to calculate an approximate Moon phase, lunar age and illuminated fraction locally in your browser, then view a 15-day lunar window.";const body=`<main class="astrology-main"><nav class="astro-crumb"><a href="/astrology">Astrology</a><span>›</span><span>Moon</span></nav><section class="astrology-hero"><p class="astrology-kicker">Local approximate lunar cycle</p><div class="moon-orb">☽</div><h1>Moon Phase Calculator</h1><p>Select any calendar date. Oracle Mirror estimates lunar age from a known new-moon epoch and the average 29.53058867-day synodic month. This is useful for a lightweight phase guide, but it is not a precision ephemeris.</p></section><section class="moon-tool"><form data-moon-form><label>Date<input type="date" name="date" required></label><button class="btn-gold" type="submit">Calculate Moon Phase</button></form><div data-moon-result aria-live="polite"></div><div class="moon-window" data-moon-window></div></section><section><h2>The eight phase labels</h2><div class="astro-card-grid">${cards(MOON_PHASES,p=>`<a href="/astrology/moon/phases/${p.slug}"><span class="astro-icon">${p.glyph}</span><strong>${p.name}</strong><small>${esc(p.astronomy)}</small></a>`)}</div></section><section class="astrology-note"><h2>How accurate is this?</h2><p>The calculator models the average synodic cycle. Real lunar phase timing varies because the Moon's orbit is not uniform, so exact event times should come from an astronomical ephemeris. Oracle Mirror deliberately labels the result approximate.</p></section><script type="module" src="/astrology.js"></script></main>`;const ld=[{"@context":"https://schema.org","@type":"WebApplication",name:"Oracle Mirror Moon Phase Calculator",url:`${HOST}/astrology/moon`,applicationCategory:"EducationApplication",operatingSystem:"Any",offers:{"@type":"Offer",price:"0",priceCurrency:"USD"},description}];return html(layout({title,description,canonical:`${HOST}/astrology/moon`,body,jsonLd:ld}),300);}

function renderPhaseHub(){const title="8 Moon Phases Explained — Astronomy & Symbolism | Oracle Mirror";const description="Learn the eight common Moon phase labels from New Moon to Waning Crescent, with the astronomy of illumination separated from modern symbolic astrology.";const body=`<main class="astrology-main"><nav class="astro-crumb"><a href="/astrology">Astrology</a><span>›</span><a href="/astrology/moon">Moon</a><span>›</span><span>Phases</span></nav><section class="astrology-hero"><h1>The Eight Moon Phases</h1><p>The phase is an illumination geometry between Sun, Earth and Moon. Symbolic meanings below belong to modern astrological practice, not to the physical cause of the phase.</p></section><div class="astro-card-grid">${cards(MOON_PHASES,p=>`<a href="/astrology/moon/phases/${p.slug}"><span class="astro-icon">${p.glyph}</span><strong>${p.name}</strong><small>${esc(p.reflection)}</small></a>`)}</div></main>`;return html(layout({title,description,canonical:`${HOST}/astrology/moon/phases`,body,jsonLd:[itemList("Eight Moon Phases",MOON_PHASES.map(p=>({name:p.name,url:`${HOST}/astrology/moon/phases/${p.slug}`})))]}));}
function renderPhasePage(slug:string){const p=phaseBySlug(slug);if(!p)return notFound();const title=`${p.name} Meaning — Astronomy & Astrology | Oracle Mirror`;const description=`${p.name}: understand the astronomical phase and its common modern symbolic astrology meaning without confusing the two.`;const body=`<main class="astrology-main"><nav class="astro-crumb"><a href="/astrology">Astrology</a><span>›</span><a href="/astrology/moon/phases">Moon Phases</a><span>›</span><span>${p.name}</span></nav><article class="astro-article"><header><div class="astro-big-icon">${p.glyph}</div><h1>${p.name}</h1><p class="astro-answer">${esc(p.astronomy)}</p></header><section><h2>Astronomy</h2><p>${esc(p.astronomy)} Phase boundaries in an eight-part model are conventions applied to a continuous change in lunar illumination.</p></section><section><h2>Modern symbolic interpretation</h2><p>${esc(p.reflection)}</p><p>This is an interpretive convention rather than a measured physical influence on human events.</p></section><div class="astrology-actions"><a class="btn-gold" href="/astrology/moon">Calculate a Moon Phase</a><a class="btn-ghost" href="/astrology/moon/phases">All Eight Phases</a></div></article></main>`;return html(layout({title,description,canonical:`${HOST}/astrology/moon/phases/${p.slug}`,body,jsonLd:[article(title,description,`${HOST}/astrology/moon/phases/${p.slug}`),breadcrumbs([["Oracle Mirror",HOST],["Moon Phases",`${HOST}/astrology/moon/phases`],[p.name,`${HOST}/astrology/moon/phases/${p.slug}`]])]}));}

function renderZodiacHub(){const title="12 Zodiac Signs — Dates, Elements, Modalities & Rulers | Oracle Mirror";const description="Explore all 12 tropical zodiac signs with approximate date ranges, elements, modalities, traditional rulers, strengths and challenges.";const body=`<main class="astrology-main"><nav class="astro-crumb"><a href="/astrology">Astrology</a><span>›</span><span>Zodiac</span></nav><section class="astrology-hero"><h1>The 12 Tropical Zodiac Signs</h1><p>These familiar calendar ranges are approximations. The Sun's exact ingress into a tropical sign varies slightly by year and time zone, so people born near a boundary need an actual ephemeris or birth-chart calculation rather than a fixed magazine date table.</p></section><div class="astro-card-grid zodiac-grid">${cards(ZODIAC_SIGNS,s=>`<a href="/astrology/zodiac/${s.slug}"><span class="astro-icon">${s.glyph}</span><strong>${s.name}</strong><small>${s.element} · ${s.modality} · ${s.ruler}</small><em>${s.dates}</em></a>`)}</div><div class="astrology-actions"><a class="btn-gold" href="/western-zodiac">Classic Zodiac Reading</a><a class="btn-ghost" href="/birth-chart">Birth Chart Tool</a></div></main>`;return html(layout({title,description,canonical:`${HOST}/astrology/zodiac`,body,jsonLd:[itemList("12 Tropical Zodiac Signs",ZODIAC_SIGNS.map(s=>({name:s.name,url:`${HOST}/astrology/zodiac/${s.slug}`})))]}));}
function renderZodiacPage(slug:string){const s=zodiacBySlug(slug);if(!s)return notFound();const title=`${s.name} Zodiac Sign — Dates, Traits, Element & Ruler | Oracle Mirror`;const description=`${s.name} (${s.glyph}) guide: ${s.element} ${s.modality} sign, traditionally ruled by ${s.ruler}, ${s.dates}. Explore strengths, challenges and symbolic themes.`;const body=`<main class="astrology-main"><nav class="astro-crumb"><a href="/astrology">Astrology</a><span>›</span><a href="/astrology/zodiac">Zodiac</a><span>›</span><span>${s.name}</span></nav><article class="astro-article"><header><div class="astro-big-icon">${s.glyph}</div><h1>${s.name} Zodiac Sign</h1><p>${s.dates}</p><div class="astro-tags"><span>${s.element}</span><span>${s.modality}</span><span>Ruler: ${s.ruler}</span></div><p class="astro-answer">${esc(s.summary)}</p></header><section><h2>${s.name} strengths</h2><p>${esc(s.strength)}</p></section><section><h2>${s.name} challenges</h2><p>${esc(s.challenge)}</p></section><section><h2>About the date range</h2><p>The dates above are a practical tropical-zodiac shortcut, not a permanent astronomical boundary at midnight on those dates. Exact Sun sign near a cusp depends on the year, time, and location used by an ephemeris.</p></section><div class="astrology-actions"><a class="btn-gold" href="/western-zodiac">Get a Zodiac Reading</a><a class="btn-ghost" href="/astrology/zodiac">All Zodiac Signs</a></div></article></main>`;return html(layout({title,description,canonical:`${HOST}/astrology/zodiac/${s.slug}`,body,jsonLd:[article(title,description,`${HOST}/astrology/zodiac/${s.slug}`),breadcrumbs([["Oracle Mirror",HOST],["Zodiac",`${HOST}/astrology/zodiac`],[s.name,`${HOST}/astrology/zodiac/${s.slug}`]])]}));}

function renderPlanetHub(){const title="Astrology Planets — Astronomy Facts & Symbolic Meanings | Oracle Mirror";const description="Explore the Sun, Moon and eight planets/dwarf planet used in modern Western astrology, with basic astronomy facts clearly separated from symbolic meanings.";const body=`<main class="astrology-main"><nav class="astro-crumb"><a href="/astrology">Astrology</a><span>›</span><span>Planets</span></nav><section class="astrology-hero"><h1>Planets in Astrology</h1><p>Astrologers conventionally call the Sun and Moon “planets” or luminaries within chart interpretation even though astronomy classifies them differently. Each page below shows the physical fact first and the symbolic tradition second.</p></section><div class="astro-card-grid">${cards(PLANETS,p=>`<a href="/astrology/planets/${p.slug}"><span class="astro-icon">${p.glyph}</span><strong>${p.name}</strong><small>${esc(p.keywords.join(" · "))}</small></a>`)}</div></main>`;return html(layout({title,description,canonical:`${HOST}/astrology/planets`,body,jsonLd:[itemList("Astrological planets and luminaries",PLANETS.map(p=>({name:p.name,url:`${HOST}/astrology/planets/${p.slug}`})))]}));}
function renderPlanetPage(slug:string){const p=planetBySlug(slug);if(!p)return notFound();const title=`${p.name} in Astrology — Symbolism & Astronomy | Oracle Mirror`;const description=`${p.name} in astrology: ${p.keywords.join(", ")}. Read the astronomical context and the traditional symbolic interpretation separately.`;const body=`<main class="astrology-main"><nav class="astro-crumb"><a href="/astrology">Astrology</a><span>›</span><a href="/astrology/planets">Planets</a><span>›</span><span>${p.name}</span></nav><article class="astro-article"><header><div class="astro-big-icon">${p.glyph}</div><h1>${p.name} in Astrology</h1><div class="astro-tags">${p.keywords.map(k=>`<span>${esc(k)}</span>`).join("")}</div></header><section><h2>Astronomy</h2><p>${esc(p.astronomy)}</p></section><section><h2>Traditional or modern astrological symbolism</h2><p>${esc(p.astrology)}</p><p>This symbolic association is part of astrological interpretation and should not be confused with a demonstrated physical influence on personality or events.</p></section>${p.retrograde?`<section><h2>${p.name} retrograde</h2><p>From Earth, ${p.name} can appear to reverse direction temporarily against the background stars because of relative orbital motion. Astrologers attach symbolic meanings to that apparent reversal; see the <a href="/astrology/retrogrades/${p.slug}">${p.name} retrograde guide</a> for the distinction.</p></section>`:""}<div class="astrology-actions"><a class="btn-gold" href="/astrology/planets">All Planets</a><a class="btn-ghost" href="/astrology/birth-chart">Birth Chart Basics</a></div></article></main>`;return html(layout({title,description,canonical:`${HOST}/astrology/planets/${p.slug}`,body,jsonLd:[article(title,description,`${HOST}/astrology/planets/${p.slug}`),breadcrumbs([["Oracle Mirror",HOST],["Planets",`${HOST}/astrology/planets`],[p.name,`${HOST}/astrology/planets/${p.slug}`]])]}));}

function renderRetrogradeHub(){const title="Planetary Retrogrades Explained — Astronomy vs Astrology | Oracle Mirror";const description="Understand apparent retrograde motion astronomically, then explore how modern astrology symbolically interprets Mercury, Venus, Mars, Jupiter and Saturn retrogrades.";const body=`<main class="astrology-main"><nav class="astro-crumb"><a href="/astrology">Astrology</a><span>›</span><span>Retrogrades</span></nav><section class="astrology-hero"><h1>Retrogrades: Apparent Motion, Symbolic Meaning</h1><p>A planet does not literally reverse its orbit around the Sun. Retrograde motion is an apparent reversal against the background stars caused by changing viewing geometry as Earth and the planet move in their orbits.</p></section><section class="astrology-note"><h2>Why astrology talks about retrogrades</h2><p>Astrological traditions treat apparent reversal as symbolically meaningful, often emphasizing review, internalization, delay, reconsideration, or altered expression. Those meanings are interpretive conventions, not astronomical measurements.</p></section><div class="astro-card-grid">${cards(RETROGRADE_PLANETS,p=>`<a href="/astrology/retrogrades/${p.slug}"><span class="astro-icon">${p.glyph}℞</span><strong>${p.name} Retrograde</strong><small>${esc(p.keywords.join(" · "))}</small></a>`)}</div></main>`;return html(layout({title,description,canonical:`${HOST}/astrology/retrogrades`,body,jsonLd:[itemList("Retrograde astrology guides",RETROGRADE_PLANETS.map(p=>({name:`${p.name} Retrograde`,url:`${HOST}/astrology/retrogrades/${p.slug}`})))]}));}
function renderRetrogradePage(slug:string){const p=RETROGRADE_PLANETS.find(x=>x.slug===slug);if(!p)return notFound();const symbolic:Record<string,string>={mercury:"review communication, assumptions, schedules and information flow rather than blaming every inconvenience on a planet",venus:"reconsider values, attraction, reciprocity, spending and relationship expectations",mars:"reassess how effort, anger, competition and initiative are being directed",jupiter:"revisit beliefs, growth plans, education and the meaning attached to opportunity",saturn:"review commitments, boundaries, responsibilities and structures that need repair"};const title=`${p.name} Retrograde Meaning — What It Is & What Astrologers Say | Oracle Mirror`;const description=`${p.name} retrograde explained: the astronomy of apparent backward motion and the symbolic interpretation used in modern astrology.`;const body=`<main class="astrology-main"><nav class="astro-crumb"><a href="/astrology">Astrology</a><span>›</span><a href="/astrology/retrogrades">Retrogrades</a><span>›</span><span>${p.name}</span></nav><article class="astro-article"><header><div class="astro-big-icon">${p.glyph}℞</div><h1>${p.name} Retrograde</h1><p class="astro-answer">Astronomically, ${p.name} retrograde is an apparent reversal in sky position caused by relative orbital geometry, not the planet physically reversing its orbit.</p></header><section><h2>Astrology interpretation</h2><p>Modern astrologers commonly use this period as a symbolic invitation to ${symbolic[p.slug]}.</p></section><section><h2>What this page does not claim</h2><p>Oracle Mirror does not claim that retrograde motion causes communication failures, breakups, financial losses, or other events. Those are astrological interpretations rather than established astronomical effects.</p></section><div class="astrology-actions"><a class="btn-gold" href="/astrology/retrogrades">All Retrogrades</a><a class="btn-ghost" href="/astrology/planets/${p.slug}">${p.name} Guide</a></div></article></main>`;return html(layout({title,description,canonical:`${HOST}/astrology/retrogrades/${p.slug}`,body,jsonLd:[article(title,description,`${HOST}/astrology/retrogrades/${p.slug}`)]}));}

function renderTransits(){const title="Astrology Transits Explained — Natal Chart vs Moving Sky | Oracle Mirror";const description="Learn what astrologers mean by a transit, how transiting planets are compared with a natal chart, and why exact timing requires real ephemeris positions.";const body=`<main class="astrology-main"><nav class="astro-crumb"><a href="/astrology">Astrology</a><span>›</span><span>Transits</span></nav><article class="astro-article"><header><h1>What Is an Astrology Transit?</h1><p class="astro-answer">A transit compares the current or future astronomical position of a celestial body with positions in a natal chart. The positions are astronomical data; the meaning assigned to the comparison is astrological interpretation.</p></header><section><h2>Three parts of a transit</h2><p><strong>Transiting planet:</strong> the body moving through the sky now. <strong>Natal point:</strong> a planet or angle in the birth chart. <strong>Aspect:</strong> the angular relationship between them, such as conjunction, opposition, square, trine, or sextile.</p></section><section><h2>Why exact timing matters</h2><p>A real transit calculator needs an ephemeris, time scale, coordinates, and aspect tolerances. Oracle Mirror does not fabricate “today's transits” from sign stereotypes. Static guide pages explain the framework; the classic Birth Chart tool remains a symbolic interpretation experience.</p></section><section><h2>Slow and fast transits</h2><p>The Moon moves quickly and produces short-lived contacts. Outer planets move slowly and can repeat the same aspect over months because direct and retrograde apparent motion carries them across the same degree more than once.</p></section><div class="astrology-actions"><a class="btn-gold" href="/birth-chart">Open Birth Chart Tool</a><a class="btn-ghost" href="/astrology/planets">Planet Meanings</a></div></article></main>`;return html(layout({title,description,canonical:`${HOST}/astrology/transits`,body,jsonLd:[article(title,description,`${HOST}/astrology/transits`)]}));}

function renderBirthGuide(){const title="Birth Chart Basics — Planets, Signs, Houses & Aspects | Oracle Mirror";const description="Learn the four main layers of a natal chart—planets, zodiac signs, houses and aspects—and why accurate birth time and location matter.";const body=`<main class="astrology-main"><nav class="astro-crumb"><a href="/astrology">Astrology</a><span>›</span><span>Birth Chart</span></nav><article class="astro-article"><header><h1>Birth Chart Basics</h1><p class="astro-answer">A natal chart is a map of calculated celestial positions for a specific date, time, and place. Astrology then interprets those positions symbolically through planets, signs, houses, angles, and aspects.</p></header><div class="birth-layer-grid"><section><h2>Planets</h2><p>Describe the symbolic function being interpreted: identity, emotion, communication, attraction, drive, growth, structure, and so on.</p></section><section><h2>Signs</h2><p>Describe the zodiacal style or mode through which a planet is interpreted. A planet and a sign are different layers.</p></section><section><h2>Houses</h2><p>Divide the local sky into twelve sectors. House cusps depend strongly on birth time, location, and the chosen house system.</p></section><section><h2>Aspects</h2><p>Measure angular relationships between chart points. Astrologers interpret those geometries as patterns of ease, tension, emphasis, or integration.</p></section></div><section><h2>Why birth time matters</h2><p>The Ascendant and house cusps move through the zodiac during the day. A guessed time can therefore produce a confidently detailed but technically wrong chart structure. Near sign boundaries, exact planetary positions can matter too.</p></section><section><h2>Tropical vs sidereal zodiac</h2><p>Western tropical astrology anchors the zodiac to the seasonal equinox/solstice framework, while sidereal systems anchor signs to stellar reference frameworks. They are different coordinate conventions and should not be silently mixed.</p></section><div class="astrology-actions"><a class="btn-gold" href="/birth-chart">Open Oracle Mirror Birth Chart</a><a class="btn-ghost" href="/astrology/zodiac">Zodiac Reference</a></div></article></main>`;return html(layout({title,description,canonical:`${HOST}/astrology/birth-chart`,body,jsonLd:[article(title,description,`${HOST}/astrology/birth-chart`)]}));}

function html(body:string,maxAge=3600){return new Response(body,{headers:{"Content-Type":"text/html; charset=UTF-8","Cache-Control":`public, max-age=${maxAge}`}});}
function notFound(){return new Response("Not found",{status:404,headers:{"Content-Type":"text/plain; charset=UTF-8"}});}
function article(headline:string,description:string,url:string){return {"@context":"https://schema.org","@type":"Article",headline,description,mainEntityOfPage:url,isPartOf:{"@type":"WebSite",name:"Oracle Mirror",url:HOST}};}
function itemList(name:string,items:{name:string;url:string}[]){return {"@context":"https://schema.org","@type":"ItemList",name,numberOfItems:items.length,itemListElement:items.map((x,i)=>({"@type":"ListItem",position:i+1,name:x.name,url:x.url}))};}
function breadcrumbs(items:[string,string][]){return {"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:items.map((x,i)=>({"@type":"ListItem",position:i+1,name:x[0],item:x[1]}))};}

export function handleAstrologyRoute(path:string):Response{
  const p=path.replace(/\/$/,"")||"/";
  if(p==="/astrology")return renderAstrologyHub();
  if(p==="/astrology/moon")return renderMoonPage();
  if(p==="/astrology/moon/phases")return renderPhaseHub();
  let m=p.match(/^\/astrology\/moon\/phases\/([a-z0-9-]+)$/);if(m)return renderPhasePage(m[1]);
  if(p==="/astrology/zodiac")return renderZodiacHub();m=p.match(/^\/astrology\/zodiac\/([a-z0-9-]+)$/);if(m)return renderZodiacPage(m[1]);
  if(p==="/astrology/planets")return renderPlanetHub();m=p.match(/^\/astrology\/planets\/([a-z0-9-]+)$/);if(m)return renderPlanetPage(m[1]);
  if(p==="/astrology/retrogrades")return renderRetrogradeHub();m=p.match(/^\/astrology\/retrogrades\/([a-z0-9-]+)$/);if(m)return renderRetrogradePage(m[1]);
  if(p==="/astrology/transits")return renderTransits();
  if(p==="/astrology/birth-chart")return renderBirthGuide();
  return notFound();
}
