export type DivinationEntry = {
  slug: string;
  name: string;
  theme: string;
  note?: string;
  colour?: string;
};

export const CRYSTALS = [
  { slug: "amethyst", name: "Amethyst", theme: "calm attention, boundaries, and reflective pause", colour: "purple" },
  { slug: "clear-quartz", name: "Clear Quartz", theme: "clarity, intention-setting, and amplification of attention", colour: "clear" },
  { slug: "rose-quartz", name: "Rose Quartz", theme: "gentleness, affection, and self-compassion", colour: "pink" },
  { slug: "smoky-quartz", name: "Smoky Quartz", theme: "grounding, steadiness, and releasing mental clutter", colour: "smoky brown" },
  { slug: "citrine", name: "Citrine", theme: "confidence, generosity, and purposeful momentum", colour: "golden yellow" },
  { slug: "black-tourmaline", name: "Black Tourmaline", theme: "boundaries, protection symbolism, and emotional steadiness", colour: "black" },
  { slug: "labradorite", name: "Labradorite", theme: "transition, imagination, and seeing unfamiliar possibilities", colour: "iridescent grey" },
  { slug: "moonstone", name: "Moonstone", theme: "cycles, receptivity, and emotional reflection", colour: "milky white" },
  { slug: "carnelian", name: "Carnelian", theme: "courage, vitality symbolism, and creative initiative", colour: "orange-red" },
  { slug: "lapis-lazuli", name: "Lapis Lazuli", theme: "truth-seeking, perspective, and thoughtful communication", colour: "deep blue" },
  { slug: "obsidian", name: "Obsidian", theme: "shadow work symbolism, honesty, and confronting avoided material", colour: "black glassy" },
  { slug: "tigers-eye", name: "Tiger's Eye", theme: "discernment, practical confidence, and measured action", colour: "gold-brown" },
  { slug: "green-aventurine", name: "Green Aventurine", theme: "opportunity symbolism, optimism, and flexible growth", colour: "green" },
  { slug: "malachite", name: "Malachite", theme: "change, pattern recognition, and emotional transformation", colour: "banded green" },
  { slug: "fluorite", name: "Fluorite", theme: "mental organization, focus, and sorting competing signals", colour: "green-purple" },
  { slug: "hematite", name: "Hematite", theme: "grounding, composure, and returning attention to the body", colour: "metallic grey" },
  { slug: "sodalite", name: "Sodalite", theme: "reasoned communication, self-trust, and intellectual honesty", colour: "royal blue" },
  { slug: "amazonite", name: "Amazonite", theme: "calm expression, boundaries, and balanced communication", colour: "blue-green" },
  { slug: "aquamarine", name: "Aquamarine", theme: "clear speech, emotional spaciousness, and calm transition", colour: "pale blue" },
  { slug: "garnet", name: "Garnet", theme: "commitment, persistence, and renewed engagement", colour: "deep red" },
  { slug: "peridot", name: "Peridot", theme: "fresh perspective, release of resentment, and constructive change", colour: "olive green" },
  { slug: "sunstone", name: "Sunstone", theme: "warmth, autonomy, and optimistic self-direction", colour: "orange-gold" },
  { slug: "lepidolite", name: "Lepidolite", theme: "rest, emotional decompression, and gentle transition", colour: "lilac" },
  { slug: "howlite", name: "Howlite", theme: "patience symbolism, quiet observation, and slowing reactivity", colour: "white veined" },
  { slug: "rhodonite", name: "Rhodonite", theme: "repair, compassion with boundaries, and relational steadiness", colour: "pink-black" },
  { slug: "chrysocolla", name: "Chrysocolla", theme: "listening, honest expression, and relational calm", colour: "blue-green" },
  { slug: "onyx", name: "Onyx", theme: "discipline, boundaries, and sustained focus", colour: "black" },
  { slug: "jasper", name: "Jasper", theme: "stability, endurance, and practical grounding", colour: "earth red" },
  { slug: "bloodstone", name: "Bloodstone", theme: "resilience symbolism, courage, and sustained effort", colour: "dark green-red" },
  { slug: "celestite", name: "Celestite", theme: "quiet contemplation, spacious thinking, and softness", colour: "pale blue" },
  { slug: "selenite", name: "Selenite", theme: "clearing symbolism, simplicity, and mental reset", colour: "white translucent" },
  { slug: "pyrite", name: "Pyrite", theme: "ambition, resourcefulness, and examining material goals", colour: "brassy gold" },
  { slug: "turquoise", name: "Turquoise", theme: "communication, protection symbolism, and relational balance", colour: "blue-green" },
  { slug: "apatite", name: "Blue Apatite", theme: "motivation, curiosity, and turning ideas into next steps", colour: "blue" },
  { slug: "unakite", name: "Unakite", theme: "integration, patience, and balancing old and new perspectives", colour: "green-pink" },
  { slug: "agate", name: "Agate", theme: "stability, layered perspective, and gradual confidence", colour: "banded multicolour" },
] as const;

export const TEA_SYMBOLS = [
  { slug: "anchor", name: "Anchor", theme: "stability, commitment, or something holding firm" },
  { slug: "arrow", name: "Arrow", theme: "direction, focus, or a message pointing toward action" },
  { slug: "bird", name: "Bird", theme: "news, movement, freedom, or a change in perspective" },
  { slug: "boat", name: "Boat", theme: "journey, transition, distance, or emotional passage" },
  { slug: "book", name: "Book", theme: "learning, hidden knowledge, study, or something not yet revealed" },
  { slug: "bottle", name: "Bottle", theme: "contained feelings, preservation, or a message kept back" },
  { slug: "bridge", name: "Bridge", theme: "connection, reconciliation, transition, or crossing a divide" },
  { slug: "butterfly", name: "Butterfly", theme: "change, lightness, emergence, or a new social phase" },
  { slug: "candle", name: "Candle", theme: "attention, hope, ritual focus, or a small light in uncertainty" },
  { slug: "cat", name: "Cat", theme: "independence, intuition symbolism, privacy, or selective trust" },
  { slug: "circle", name: "Circle", theme: "completion, repetition, belonging, or a pattern returning" },
  { slug: "clock", name: "Clock", theme: "timing, deadlines, patience, or awareness of a limited window" },
  { slug: "cloud", name: "Cloud", theme: "uncertainty, mood, confusion, or something not yet clearly seen" },
  { slug: "crown", name: "Crown", theme: "recognition, responsibility, pride, or visibility" },
  { slug: "dog", name: "Dog", theme: "loyalty, companionship, support, or dependable connection" },
  { slug: "door", name: "Door", theme: "opportunity, threshold, choice, or entry into a new situation" },
  { slug: "dragon", name: "Dragon", theme: "power, challenge, imagination, or confronting a large fear" },
  { slug: "eye", name: "Eye", theme: "awareness, observation, scrutiny, or seeing what was missed" },
  { slug: "feather", name: "Feather", theme: "lightness, message symbolism, release, or a softer approach" },
  { slug: "fish", name: "Fish", theme: "flow, abundance symbolism, adaptability, or emotional depth" },
  { slug: "flower", name: "Flower", theme: "growth, appreciation, attraction, or something coming into bloom" },
  { slug: "fork", name: "Fork", theme: "choice, divergence, competing paths, or a decision point" },
  { slug: "fox", name: "Fox", theme: "strategy, adaptability, caution, or reading a situation carefully" },
  { slug: "heart", name: "Heart", theme: "affection, attachment, vulnerability, or an emotional priority" },
  { slug: "horse", name: "Horse", theme: "drive, freedom, progress, or disciplined momentum" },
  { slug: "key", name: "Key", theme: "access, solution, permission, or a useful insight" },
  { slug: "ladder", name: "Ladder", theme: "progress, ambition, gradual advancement, or changing status" },
  { slug: "moon", name: "Moon", theme: "cycles, privacy, imagination, or fluctuating feelings" },
  { slug: "mountain", name: "Mountain", theme: "challenge, endurance, distance, or a goal requiring effort" },
  { slug: "ring", name: "Ring", theme: "commitment, agreement, repetition, or a bond" },
  { slug: "road", name: "Road", theme: "direction, travel, life transition, or the path ahead" },
  { slug: "snake", name: "Snake", theme: "change, caution, complexity, or something requiring discernment" },
  { slug: "spider", name: "Spider", theme: "patience, networks, intricate work, or feeling caught in a pattern" },
  { slug: "star", name: "Star", theme: "hope, aspiration, visibility, or a guiding ideal" },
  { slug: "sun", name: "Sun", theme: "clarity, confidence, warmth, or a matter becoming more visible" },
  { slug: "tree", name: "Tree", theme: "roots, family, stability, growth, or long-term development" },
  { slug: "triangle", name: "Triangle", theme: "tension among three factors, structure, or focused energy" },
  { slug: "umbrella", name: "Umbrella", theme: "protection, preparation, boundaries, or shelter from pressure" },
  { slug: "wheel", name: "Wheel", theme: "cycles, change, momentum, or circumstances turning" },
  { slug: "wolf", name: "Wolf", theme: "instinct, group dynamics, independence, or guarded strength" },
] as const;

export const WAX_SYMBOLS = [
  { slug: "arch", name: "Arch", theme: "transition, passage, or moving under a new set of conditions" },
  { slug: "bird", name: "Bird", theme: "news, movement, perspective, or a wish for freedom" },
  { slug: "broken-line", name: "Broken Line", theme: "interruption, changing plans, or a process needing repair" },
  { slug: "bubble", name: "Bubble", theme: "temporary excitement, fragile expectations, or something still forming" },
  { slug: "circle", name: "Circle", theme: "completion, repetition, return, or a closed loop" },
  { slug: "crescent", name: "Crescent", theme: "a beginning phase, partial visibility, or something still developing" },
  { slug: "cross", name: "Cross", theme: "intersection, burden, commitment, or conflicting priorities" },
  { slug: "crown", name: "Crown", theme: "recognition, responsibility, pride, or visibility" },
  { slug: "drip-trail", name: "Drip Trail", theme: "gradual progress, emotional spillover, or a process unfolding slowly" },
  { slug: "eye", name: "Eye", theme: "attention, scrutiny, awareness, or the need to observe carefully" },
  { slug: "flower", name: "Flower", theme: "growth, appreciation, attraction, or an opening" },
  { slug: "heart", name: "Heart", theme: "affection, emotional focus, vulnerability, or relationship concerns" },
  { slug: "hook", name: "Hook", theme: "attachment, unfinished business, or something pulling attention back" },
  { slug: "key", name: "Key", theme: "access, solution, permission, or a useful clue" },
  { slug: "ladder", name: "Ladder", theme: "stepwise progress, ambition, or moving between levels" },
  { slug: "leaf", name: "Leaf", theme: "renewal, seasonal change, growth, or adaptation" },
  { slug: "mountain", name: "Mountain", theme: "challenge, endurance, resistance, or a demanding goal" },
  { slug: "path", name: "Path", theme: "direction, sequence, travel, or the next practical step" },
  { slug: "ring", name: "Ring", theme: "commitment, repetition, agreement, or a recurring concern" },
  { slug: "shell", name: "Shell", theme: "privacy, retreat, protection, or keeping something contained" },
  { slug: "spiral", name: "Spiral", theme: "recurring thought, deepening reflection, or revisiting a pattern" },
  { slug: "star", name: "Star", theme: "hope, aspiration, inspiration, or a guiding ideal" },
  { slug: "tower", name: "Tower", theme: "structure, isolation, authority, or a rigid situation" },
  { slug: "wave", name: "Wave", theme: "emotion, fluctuation, momentum, or a changing rhythm" },
] as const;

export const SCRYING_METHODS = [
  { slug: "crystal-ball-scrying", name: "Crystal Ball Scrying", theme: "soft-focus observation using a reflective or translucent sphere", note: "Keep the gaze relaxed, notice spontaneous imagery, and treat impressions as imagination-led prompts rather than external messages." },
  { slug: "black-mirror-scrying", name: "Black Mirror Scrying", theme: "gazing into a dark reflective surface to encourage free association", note: "Use low distraction, not total darkness; stop if staring becomes uncomfortable, dissociative, or distressing." },
  { slug: "water-scrying", name: "Water Scrying", theme: "using reflections and movement on water as a focus for symbolic association", note: "Notice shapes, memories, and emotions without treating random movement as evidence of future events." },
  { slug: "flame-gazing", name: "Flame Gazing", theme: "briefly observing a candle flame as a concentration and reflection exercise", note: "Keep fire safety first, avoid prolonged staring, and never infer health or danger from flame behaviour." },
  { slug: "smoke-scrying", name: "Smoke Scrying", theme: "observing smoke movement as a prompt for metaphor and pattern recognition", note: "Ventilate safely and do not deliberately inhale smoke; use the shapes as imaginative prompts, not omens with factual authority." },
  { slug: "cloud-scrying", name: "Cloud Scrying", theme: "finding spontaneous images in clouds and using them as reflective metaphors", note: "This works through pareidolia—the normal tendency to perceive meaningful forms in ambiguous patterns—so personal associations are the point." },
] as const;

export const PENDULUM_GUIDES = [
  { slug: "how-to-use-a-pendulum", name: "How to Use a Pendulum", theme: "a simple, non-predictive pendulum reflection routine", note: "Set a question, define movement labels in advance, keep the hand supported, and use the result to notice your own reaction rather than outsource the decision." },
  { slug: "yes-no-maybe", name: "Yes, No & Maybe Pendulum Patterns", theme: "a bounded symbolic answer set for reflective use", note: "Predefine possible outcomes before the swing. Small unconscious muscle movements can influence motion, so treat the result as a prompt rather than an external verdict." },
  { slug: "ideomotor-effect", name: "Pendulums & the Ideomotor Effect", theme: "why pendulums can move without conscious intention", note: "Tiny involuntary muscle movements can produce visible pendulum motion. This helps explain why a pendulum may feel responsive without requiring a supernatural mechanism." },
  { slug: "pendulum-ethics", name: "Pendulum Ethics & Better Questions", theme: "how to avoid coercive, fear-based, or high-stakes pendulum use", note: "Do not use pendulums to diagnose illness, accuse people, predict death, make safety decisions, or replace professional medical, legal, financial, or mental-health guidance." },
] as const;

export const DIVINATION_GUIDES = [
  { slug: "history", name: "History & Traditions", theme: "how divination practices changed across cultures and periods", note: "Treat broad historical claims cautiously: practices often developed independently, changed names, and were reshaped by later occult revivals." },
  { slug: "pareidolia", name: "Pareidolia & Pattern Recognition", theme: "why faces, animals, letters, and scenes appear in ambiguous forms", note: "Pareidolia is a normal perceptual process. In reflective divination it can be used creatively without claiming that the pattern was externally sent." },
  { slug: "ritual-safety", name: "Ritual Safety", theme: "practical safety for candles, smoke, staring practices, and emotionally intense readings", note: "Keep fire, ventilation, eye comfort, sleep, and emotional wellbeing ahead of ritual aesthetics. Stop practices that cause discomfort or distress." },
  { slug: "symbol-journaling", name: "Symbol Journaling", theme: "a method for tracking personal associations instead of memorizing fixed meanings", note: "Record the image, your immediate feeling, personal memories, context, and what happened later. Over time this builds a personal symbolic vocabulary without pretending universal certainty." },
  { slug: "tradition-vs-evidence", name: "Tradition vs Evidence", theme: "how to enjoy divination without confusing cultural tradition with scientific validation", note: "Historical use and personal meaning can be culturally interesting, but neither automatically establishes predictive accuracy, medical efficacy, or supernatural causation." },
] as const;
