export type LenormandCard = {
  number: number;
  slug: string;
  name: string;
  symbol: string;
  playingCard: string;
  polarity: "light" | "neutral" | "shadow";
  keywords: string[];
  core: string;
  light: string;
  challenge: string;
  love: string;
  work: string;
  reflection: string;
};

export const LENORMAND_CARDS: LenormandCard[] = [
  { number: 1, slug: "rider", name: "Rider", symbol: "🐎", playingCard: "9 of Hearts", polarity: "light", keywords: ["news", "arrival", "movement"], core: "The Rider brings motion: news, a visitor, a message, or a development that changes the pace of a situation.", light: "Act on useful information while it is fresh and let momentum work in your favor.", challenge: "Speed can create shallow decisions if every new signal is treated as urgent.", love: "Expect movement, contact, or a relationship conversation that breaks a period of waiting.", work: "A lead, update, invitation, or fast-moving opportunity may require a prompt response.", reflection: "What new information deserves your attention now?" },
  { number: 2, slug: "clover", name: "Clover", symbol: "🍀", playingCard: "6 of Diamonds", polarity: "light", keywords: ["luck", "chance", "small opening"], core: "Clover points to a modest but timely opening: good luck, relief, or a small chance that becomes useful if noticed quickly.", light: "Say yes to the low-risk opportunity that could create disproportionate upside.", challenge: "A lucky break can be missed through overthinking or wasted through carelessness.", love: "A lighthearted moment or unexpected invitation can soften relationship tension.", work: "A small win, useful contact, or lucky break may improve the week more than a grand plan.", reflection: "Where is the small opening you may be overlooking?" },
  { number: 3, slug: "ship", name: "Ship", symbol: "⛵", playingCard: "10 of Spades", polarity: "neutral", keywords: ["journey", "distance", "expansion"], core: "The Ship widens the horizon through travel, distance, trade, exploration, or a desire to move beyond familiar limits.", light: "Expansion is favored when curiosity is paired with a workable route.", challenge: "Restlessness can disguise dissatisfaction that travel alone will not solve.", love: "Distance, travel, or a shared wish for something different may shape the relationship.", work: "Think beyond the current market, role, or location; growth may sit outside the usual boundary.", reflection: "What horizon are you ready to explore more seriously?" },
  { number: 4, slug: "house", name: "House", symbol: "🏠", playingCard: "King of Hearts", polarity: "light", keywords: ["home", "stability", "foundation"], core: "The House centers on home, family, property, safety, routine, and the structures that make life feel dependable.", light: "Strengthen the foundation before chasing expansion.", challenge: "Security can become confinement when familiar patterns are protected simply because they are familiar.", love: "Domestic life, family expectations, or the wish for stability moves to the foreground.", work: "Reliable systems, a stable employer, or home-based work may matter more than novelty.", reflection: "What foundation needs reinforcement?" },
  { number: 5, slug: "tree", name: "Tree", symbol: "🌳", playingCard: "7 of Hearts", polarity: "light", keywords: ["growth", "health", "roots"], core: "The Tree suggests slow growth, rootedness, vitality, ancestry, and processes that become meaningful over a long horizon.", light: "Choose sustainable progress over dramatic acceleration.", challenge: "Slow development can feel frustrating when you expect an immediate result.", love: "A relationship may be deepening gradually through trust and shared history.", work: "Long-term skill building, culture, and sustainable systems matter more than quick wins.", reflection: "What deserves patient cultivation rather than pressure?" },
  { number: 6, slug: "clouds", name: "Clouds", symbol: "☁️", playingCard: "King of Clubs", polarity: "shadow", keywords: ["confusion", "uncertainty", "mixed signals"], core: "Clouds describe ambiguity, shifting perception, incomplete information, or a situation that is difficult to read clearly for now.", light: "Delay certainty until the facts improve; confusion is sometimes temporary weather.", challenge: "Anxiety can fill missing information with the worst possible explanation.", love: "Mixed signals or unclear expectations need clarification before conclusions are drawn.", work: "Avoid irreversible choices while key facts, ownership, or direction remain vague.", reflection: "Which conclusion are you making before the evidence is clear?" },
  { number: 7, slug: "snake", name: "Snake", symbol: "🐍", playingCard: "Queen of Clubs", polarity: "shadow", keywords: ["complexity", "strategy", "detour"], core: "The Snake points to complexity, indirect routes, temptation, strategy, or a problem that requires more care than it first appears.", light: "Use intelligence, patience, and strategic awareness rather than confronting complexity head-on.", challenge: "Suspicion can become self-defeating if every complication is interpreted as betrayal.", love: "Jealousy, temptation, or a complicated triangle may need calm boundaries and facts.", work: "Read incentives carefully; office politics or an indirect route may matter more than the formal plan.", reflection: "Where would strategy serve you better than reaction?" },
  { number: 8, slug: "coffin", name: "Coffin", symbol: "⚰️", playingCard: "9 of Diamonds", polarity: "shadow", keywords: ["ending", "closure", "pause"], core: "The Coffin marks an ending, closure, depletion, or a necessary pause that makes continuation in the old form unlikely.", light: "Completion can create room for recovery and a more honest next chapter.", challenge: "Holding on after something has clearly ended can turn grief into stagnation.", love: "A chapter, pattern, or expectation may need to end even if the relationship itself continues.", work: "A project, role, or method may have reached the point where closure is more useful than rescue.", reflection: "What is asking to be finished rather than revived?" },
  { number: 9, slug: "bouquet", name: "Bouquet", symbol: "💐", playingCard: "Queen of Spades", polarity: "light", keywords: ["gift", "beauty", "appreciation"], core: "The Bouquet brings appreciation, pleasure, charm, generosity, gifts, invitations, and the social warmth of being welcomed.", light: "Receive the compliment, invitation, or kindness without immediately minimizing it.", challenge: "Charm can become superficial if appearances replace substance.", love: "Affection, romance, or an enjoyable invitation can refresh connection.", work: "Recognition, positive feedback, hospitality, or presentation may open doors.", reflection: "What deserves to be appreciated more openly?" },
  { number: 10, slug: "scythe", name: "Scythe", symbol: "🌾", playingCard: "Jack of Diamonds", polarity: "shadow", keywords: ["cut", "decision", "sudden change"], core: "The Scythe signals a sharp cut, sudden decision, separation, harvest, or moment when delay becomes more costly than action.", light: "A clean decision can prevent a longer period of uncertainty.", challenge: "Acting too quickly can turn necessary decisiveness into avoidable damage.", love: "A boundary, decisive conversation, or abrupt shift may change the relationship dynamic.", work: "A cancellation, restructuring, deadline, or decisive cut may demand immediate prioritization.", reflection: "What needs a clean decision rather than another delay?" },
  { number: 11, slug: "whip", name: "Whip", symbol: "〰️", playingCard: "Jack of Clubs", polarity: "shadow", keywords: ["conflict", "repetition", "intensity"], core: "The Whip describes repeated friction, debate, intensity, practice, or a pattern that keeps returning until handled differently.", light: "Repetition can build mastery when directed toward practice rather than argument.", challenge: "Conflict becomes corrosive when the same fight is replayed without new information.", love: "Recurring arguments or strong chemistry may both be present; patterns matter more than one incident.", work: "Rework, negotiation, competition, or repetitive pressure may dominate the current cycle.", reflection: "What keeps repeating because the pattern itself has not changed?" },
  { number: 12, slug: "birds", name: "Birds", symbol: "🐦", playingCard: "7 of Diamonds", polarity: "neutral", keywords: ["conversation", "nerves", "buzz"], core: "The Birds bring conversation, chatter, nervous energy, calls, meetings, and information moving quickly between people.", light: "Talking something through can release tension and reveal the useful signal inside the noise.", challenge: "Rumor, over-analysis, and constant checking can amplify anxiety.", love: "A relationship conversation or flurry of messages may be more emotionally charged than expected.", work: "Meetings, calls, negotiations, and rapid exchanges require careful listening.", reflection: "Which conversation would reduce uncertainty instead of feeding it?" },
  { number: 13, slug: "child", name: "Child", symbol: "🧒", playingCard: "Jack of Spades", polarity: "neutral", keywords: ["beginning", "small", "curiosity"], core: "The Child represents beginnings, simplicity, small scale, curiosity, innocence, or something still early in development.", light: "Start small enough to learn quickly and preserve curiosity.", challenge: "Naivety can become risk when inexperience is mistaken for certainty.", love: "A fresh start, playful tone, or new stage may make the relationship feel less burdened.", work: "Treat a new project as an experiment rather than demanding mature results immediately.", reflection: "What would become easier if you approached it as a beginner?" },
  { number: 14, slug: "fox", name: "Fox", symbol: "🦊", playingCard: "9 of Clubs", polarity: "neutral", keywords: ["work", "caution", "self-interest"], core: "The Fox points to work, practical intelligence, caution, self-interest, and the need to verify what appears professionally polished.", light: "Use discernment and competence; smart work often beats brute effort.", challenge: "Excessive suspicion can make cooperation impossible.", love: "Check whether actions match words, especially where convenience or self-protection shapes behavior.", work: "This card strongly favors diligence, verification, and awareness of incentives in professional matters.", reflection: "What deserves verification rather than assumption?" },
  { number: 15, slug: "bear", name: "Bear", symbol: "🐻", playingCard: "10 of Clubs", polarity: "neutral", keywords: ["power", "resources", "protection"], core: "The Bear represents power, authority, resources, protection, appetite, and the influence of someone or something substantial.", light: "Use strength to protect, resource, and stabilize rather than dominate.", challenge: "Control, possessiveness, or overprotection can shrink the space others need.", love: "Strong protective feelings may be supportive or controlling depending on how boundaries are handled.", work: "A boss, investor, budget, major client, or institutional power may shape the outcome.", reflection: "How can you use influence without overusing control?" },
  { number: 16, slug: "stars", name: "Stars", symbol: "⭐", playingCard: "6 of Hearts", polarity: "light", keywords: ["guidance", "hope", "clarity"], core: "The Stars suggest guidance, hope, alignment, visibility, networks, and a clearer sense of direction after uncertainty.", light: "Follow the direction that becomes more coherent as you zoom out.", challenge: "Idealism needs grounding or inspiration can remain only a beautiful idea.", love: "Shared hopes and a sense of emotional direction support connection.", work: "Long-term vision, online networks, reputation, or strategic clarity may become especially useful.", reflection: "What direction still feels meaningful when you look beyond immediate pressure?" },
  { number: 17, slug: "stork", name: "Stork", symbol: "🕊️", playingCard: "Queen of Hearts", polarity: "light", keywords: ["change", "upgrade", "transition"], core: "The Stork brings constructive change, movement, relocation, improvement, or a transition toward a different arrangement.", light: "Make the change that improves the system rather than merely disrupting it.", challenge: "Constant upgrading can become restlessness if nothing is allowed to settle.", love: "A relationship may change form through moving, commitment, family developments, or renewed habits.", work: "Role changes, relocation, process improvement, or promotion may be in view.", reflection: "Which change would genuinely improve the current arrangement?" },
  { number: 18, slug: "dog", name: "Dog", symbol: "🐕", playingCard: "10 of Hearts", polarity: "light", keywords: ["loyalty", "friendship", "support"], core: "The Dog represents loyalty, friendship, reliability, trust, and the person who remains supportive when circumstances are less glamorous.", light: "Lean on proven trust and be the kind of ally you would want beside you.", challenge: "Loyalty should not require ignoring harmful behavior or obvious incompatibility.", love: "Friendship, reliability, and emotional safety may matter more than drama.", work: "A trusted colleague, partner, or dependable network can be a decisive asset.", reflection: "Who has earned your trust through consistency?" },
  { number: 19, slug: "tower", name: "Tower", symbol: "🏛️", playingCard: "6 of Spades", polarity: "neutral", keywords: ["institution", "distance", "independence"], core: "The Tower points to institutions, boundaries, authority, solitude, hierarchy, and the perspective gained from stepping back.", light: "Healthy distance can create objectivity and stronger boundaries.", challenge: "Independence can harden into isolation or bureaucracy.", love: "Emotional distance or a need for personal space may need to be named clearly.", work: "Corporations, government, formal structures, seniority, or policy may dominate the situation.", reflection: "Would more distance improve your perspective or merely avoid the issue?" },
  { number: 20, slug: "garden", name: "Garden", symbol: "🌿", playingCard: "8 of Spades", polarity: "neutral", keywords: ["public", "community", "network"], core: "The Garden represents public life, community, events, networks, audiences, visibility, and places where many people gather.", light: "Connection expands when you participate rather than waiting to be discovered.", challenge: "Public approval can become a poor substitute for private conviction.", love: "Social circles, public events, or being seen together may influence the relationship.", work: "Networking, events, community, PR, or an external audience can create opportunity.", reflection: "Where would showing up publicly create useful connection?" },
  { number: 21, slug: "mountain", name: "Mountain", symbol: "⛰️", playingCard: "8 of Clubs", polarity: "shadow", keywords: ["obstacle", "delay", "endurance"], core: "The Mountain describes a significant obstacle, delay, distance, or immovable condition that requires patience and a different route.", light: "A real barrier becomes easier to manage once it is acknowledged rather than minimized.", challenge: "Stubbornly pushing the same route can waste the energy needed to go around the obstacle.", love: "Distance, resistance, or an unresolved barrier may slow progress.", work: "A structural blocker, approval process, resource gap, or slow institution may need an alternate plan.", reflection: "What obstacle becomes manageable if you stop pretending it is small?" },
  { number: 22, slug: "crossroads", name: "Crossroads", symbol: "🛤️", playingCard: "Queen of Diamonds", polarity: "neutral", keywords: ["choice", "options", "divergence"], core: "Crossroads signals options, branching paths, alternatives, and a decision that becomes meaningful because not every route can be taken.", light: "Clarify criteria before choosing and let the decision close some doors on purpose.", challenge: "Keeping every option open can become its own form of paralysis.", love: "A relationship choice or competing priorities may need a direct decision.", work: "Several viable routes may exist; define the trade-off rather than searching for a cost-free option.", reflection: "What criterion would make this choice simpler?" },
  { number: 23, slug: "mice", name: "Mice", symbol: "🐭", playingCard: "7 of Clubs", polarity: "shadow", keywords: ["loss", "stress", "erosion"], core: "The Mice point to small losses, stress, erosion, worry, inefficiency, or something gradually being consumed around the edges.", light: "Small leaks can often be fixed before they become major damage.", challenge: "Chronic worry may consume more energy than the original problem.", love: "Stress, resentment, or small recurring disappointments may be weakening connection.", work: "Watch hidden costs, rework, attrition, waste, or tasks that quietly eat capacity.", reflection: "What small leak deserves attention before it grows?" },
  { number: 24, slug: "heart", name: "Heart", symbol: "❤️", playingCard: "Jack of Hearts", polarity: "light", keywords: ["love", "affection", "desire"], core: "The Heart centers affection, love, warmth, desire, compassion, and what matters because you genuinely care about it.", light: "Let sincere feeling inform the decision without abandoning judgment.", challenge: "Desire can distort perception when wanting something becomes evidence that it is right.", love: "Affection and emotional openness are central; this is one of Lenormand's clearest relationship cards.", work: "Motivation, passion, customer care, or work that feels meaningful may matter more than status alone.", reflection: "What do you care about enough to treat it with honesty?" },
  { number: 25, slug: "ring", name: "Ring", symbol: "💍", playingCard: "Ace of Clubs", polarity: "light", keywords: ["commitment", "agreement", "cycle"], core: "The Ring represents commitment, contracts, agreements, promises, partnership, and cycles created through repetition.", light: "Make commitments explicit enough that everyone knows what is being promised.", challenge: "A commitment can become a trap when maintained automatically after its purpose has disappeared.", love: "Commitment, exclusivity, engagement, partnership, or the terms of a relationship move to the foreground.", work: "Contracts, retainers, partnerships, recurring business, or formal agreements are emphasized.", reflection: "Which commitment deserves clearer terms?" },
  { number: 26, slug: "book", name: "Book", symbol: "📖", playingCard: "10 of Diamonds", polarity: "neutral", keywords: ["knowledge", "secret", "study"], core: "The Book points to knowledge, study, research, a secret, or information that is not yet open to everyone involved.", light: "Learn before acting and respect information that needs proper context.", challenge: "Secrecy can become manipulation when relevant facts are deliberately withheld.", love: "Something private, unspoken, or not yet understood may shape the relationship.", work: "Research, training, confidential material, expertise, or undisclosed information may matter.", reflection: "What do you need to learn before deciding?" },
  { number: 27, slug: "letter", name: "Letter", symbol: "✉️", playingCard: "7 of Spades", polarity: "neutral", keywords: ["message", "document", "record"], core: "The Letter represents written communication, documents, applications, contracts, records, email, or information that becomes concrete in text.", light: "Put important details in writing and read the fine print.", challenge: "A message can be misunderstood when tone or context is missing.", love: "Texts, messages, letters, or a written agreement may carry more weight than casual conversation.", work: "Applications, contracts, reports, email, documentation, or formal written notice are highlighted.", reflection: "What should be written down rather than left implicit?" },
  { number: 28, slug: "man", name: "Man", symbol: "👤", playingCard: "Ace of Hearts", polarity: "neutral", keywords: ["person", "significator", "agency"], core: "The Man is traditionally a significator card representing a person in the reading; modern readers may assign it to whichever person or role fits the context.", light: "Focus on the agency, choices, and perspective of the person this card represents.", challenge: "Avoid forcing gender assumptions when the card can simply function as a chosen person marker.", love: "This card may represent a partner, seeker, or relevant person depending on the reading setup.", work: "A specific person's decisions or influence may be central to the professional situation.", reflection: "Whose choices matter most in this situation?" },
  { number: 29, slug: "woman", name: "Woman", symbol: "👤", playingCard: "Ace of Spades", polarity: "neutral", keywords: ["person", "significator", "agency"], core: "The Woman is traditionally a significator card representing a person in the reading; modern readers may assign it to whichever person or role fits the context.", light: "Center the perspective and agency of the person this card represents rather than treating them as a symbol only.", challenge: "Traditional labels need not dictate gender identity or relationship role in a modern reading.", love: "This card may represent a partner, seeker, or relevant person depending on the reading setup.", work: "A particular person's actions, authority, or perspective may shape the outcome.", reflection: "Which person's perspective needs to be understood more clearly?" },
  { number: 30, slug: "lily", name: "Lily", symbol: "⚜️", playingCard: "King of Spades", polarity: "neutral", keywords: ["maturity", "peace", "ethics"], core: "The Lily suggests maturity, calm, ethics, experience, peace, sensuality, and the steadier perspective that comes with time.", light: "Choose the response that will still feel dignified after the immediate emotion passes.", challenge: "Calm can become passivity if harmony is preserved by avoiding a necessary issue.", love: "Mature affection, sensuality, patience, or an age/experience difference may be relevant.", work: "Experience, seniority, ethics, mediation, or a seasoned advisor can help stabilize the situation.", reflection: "What would the mature version of this decision look like?" },
  { number: 31, slug: "sun", name: "Sun", symbol: "☀️", playingCard: "Ace of Diamonds", polarity: "light", keywords: ["success", "energy", "visibility"], core: "The Sun brings energy, confidence, success, visibility, warmth, and the clarity that comes when a situation is fully illuminated.", light: "Put energy behind what is working and allow success to become visible.", challenge: "Confidence can overheat into arrogance or unrealistic certainty.", love: "Warmth, attraction, happiness, and greater openness support connection.", work: "Recognition, momentum, leadership, strong results, or public success may be emphasized.", reflection: "Where can you act with more confident clarity?" },
  { number: 32, slug: "moon", name: "Moon", symbol: "🌙", playingCard: "8 of Hearts", polarity: "neutral", keywords: ["recognition", "emotion", "imagination"], core: "The Moon points to emotion, intuition, imagination, reputation, recognition, and the changing inner response to what is happening.", light: "Creative sensitivity and emotional intelligence can reveal what metrics alone miss.", challenge: "Mood can distort judgment when every feeling is treated as a fact.", love: "Romance, emotional sensitivity, longing, or the need for reassurance may intensify.", work: "Recognition, reputation, creative work, or emotionally intelligent leadership may matter.", reflection: "Which feeling contains useful information, and which is only weather?" },
  { number: 33, slug: "key", name: "Key", symbol: "🔑", playingCard: "8 of Diamonds", polarity: "light", keywords: ["solution", "certainty", "access"], core: "The Key marks a solution, breakthrough, access point, important certainty, or the piece that makes the rest of the situation understandable.", light: "Prioritize what unlocks the problem rather than optimizing minor details.", challenge: "One strong solution can create tunnel vision if alternative risks are ignored.", love: "A decisive realization, important conversation, or clear commitment may unlock progress.", work: "A critical insight, approval, credential, contact, or solution may remove the main blocker.", reflection: "What one thing would unlock disproportionate progress?" },
  { number: 34, slug: "fish", name: "Fish", symbol: "🐟", playingCard: "King of Diamonds", polarity: "light", keywords: ["money", "flow", "independence"], core: "The Fish represent money, commerce, abundance, liquidity, independence, and resources moving freely through a system.", light: "Improve the flow of resources rather than focusing only on accumulation.", challenge: "More is not always better if growth lacks control, purpose, or sustainability.", love: "Independence and values around money may need to coexist with emotional closeness.", work: "Revenue, cash flow, trade, entrepreneurship, pricing, or financial autonomy are strongly emphasized.", reflection: "Where could better flow matter more than simply having more?" },
  { number: 35, slug: "anchor", name: "Anchor", symbol: "⚓", playingCard: "9 of Spades", polarity: "light", keywords: ["stability", "work", "persistence"], core: "The Anchor represents stability, persistence, security, vocation, staying power, and the point that keeps a situation from drifting.", light: "Commit to the structure that provides dependable long-term support.", challenge: "Stability can become stuckness when staying is valued more than growing.", love: "Reliability, long-term commitment, and emotional steadiness may be central.", work: "Career, stable employment, long-term contracts, or persistence through a slow cycle are highlighted.", reflection: "What deserves to become more stable—and what are you merely clinging to?" },
  { number: 36, slug: "cross", name: "Cross", symbol: "✚", playingCard: "6 of Clubs", polarity: "shadow", keywords: ["burden", "meaning", "responsibility"], core: "The Cross points to burden, responsibility, difficulty, meaning, duty, or an experience that feels weighty because it cannot simply be shrugged off.", light: "Choose which responsibilities are truly yours and carry them with purpose rather than resentment.", challenge: "Suffering can become identity if every burden is treated as unavoidable or noble.", love: "A relationship may be carrying grief, duty, sacrifice, or a serious test that needs compassionate honesty.", work: "Heavy responsibility, pressure, duty, or a demanding obligation may need clearer limits.", reflection: "Which burden is meaningful to carry, and which should be put down?" },
];

export const LENORMAND_BY_SLUG = new Map(LENORMAND_CARDS.map((card) => [card.slug, card]));

export function lenormandBySlug(slug: string): LenormandCard | undefined {
  return LENORMAND_BY_SLUG.get(slug.toLowerCase());
}
