export type NumerologyNumber = {
  value: number;
  name: string;
  keywords: string[];
  core: string;
  strength: string;
  challenge: string;
  love: string;
  work: string;
  reflection: string;
  master?: boolean;
};

export type CoreNumberGuide = {
  slug: string;
  name: string;
  shortName: string;
  source: string;
  meaning: string;
  method: string;
};

export const NUMEROLOGY_NUMBERS: NumerologyNumber[] = [
  { value: 1, name: "The Initiator", keywords: ["independence", "initiative", "identity"], core: "One emphasizes beginnings, self-direction, and the willingness to move first when no path is obvious.", strength: "At its best, 1 acts decisively, trusts its own judgment, and creates momentum instead of waiting for permission.", challenge: "The shadow of 1 is isolation, impatience, or confusing independence with the need to do everything alone.", love: "In relationships, 1 benefits from room to remain individual while learning that partnership does not diminish autonomy.", work: "At work, 1 favors ownership, entrepreneurship, leadership, and roles where initiative matters more than constant supervision.", reflection: "Where would one clear act of initiative change the situation?" },
  { value: 2, name: "The Diplomat", keywords: ["cooperation", "sensitivity", "balance"], core: "Two emphasizes relationship, receptivity, timing, and the intelligence required to notice what exists between people rather than only within them.", strength: "At its best, 2 listens well, mediates differences, and builds trust through patience and subtle perception.", challenge: "The shadow of 2 is indecision, over-accommodation, or giving other people's reactions too much authority.", love: "In relationships, 2 seeks reciprocity, emotional attunement, and a sense that both people are genuinely being considered.", work: "At work, 2 suits collaboration, coordination, diplomacy, support, negotiation, and roles where interpersonal judgment matters.", reflection: "Where could cooperation accomplish more than pushing harder alone?" },
  { value: 3, name: "The Communicator", keywords: ["expression", "creativity", "sociability"], core: "Three emphasizes expression, imagination, language, humor, and the ability to turn inner experience into something others can understand or enjoy.", strength: "At its best, 3 brings ideas to life, connects people, and makes difficult material easier to approach through creativity.", challenge: "The shadow of 3 is scattering attention, performing instead of communicating honestly, or avoiding depth through constant stimulation.", love: "In relationships, 3 needs conversation, play, curiosity, and enough openness for feelings to be spoken rather than guessed.", work: "At work, 3 favors communication, sales, teaching, design, media, performance, writing, and idea-rich environments.", reflection: "What needs to be expressed more clearly, simply, or creatively?" },
  { value: 4, name: "The Builder", keywords: ["structure", "reliability", "discipline"], core: "Four emphasizes foundations, repeatable effort, order, and the patient work required to turn an idea into something dependable.", strength: "At its best, 4 plans carefully, follows through, and creates systems that remain useful after the initial enthusiasm fades.", challenge: "The shadow of 4 is rigidity, over-control, pessimism, or mistaking familiar routines for the only safe option.", love: "In relationships, 4 tends to show care through reliability, consistency, practical support, and keeping commitments.", work: "At work, 4 suits operations, engineering, finance, logistics, administration, craft, and any environment where precision compounds over time.", reflection: "What foundation would make the next stage easier to sustain?" },
  { value: 5, name: "The Explorer", keywords: ["freedom", "change", "adaptability"], core: "Five emphasizes movement, variety, experimentation, and learning through direct experience rather than theory alone.", strength: "At its best, 5 adapts quickly, spots new possibilities, and remains resourceful when plans change unexpectedly.", challenge: "The shadow of 5 is restlessness, impulsiveness, or abandoning useful commitments simply because novelty appears elsewhere.", love: "In relationships, 5 needs freshness, curiosity, and freedom within commitment rather than freedom from all commitment.", work: "At work, 5 thrives in dynamic roles involving travel, sales, entrepreneurship, media, problem-solving, or changing markets.", reflection: "Which change would create real freedom rather than temporary escape?" },
  { value: 6, name: "The Steward", keywords: ["care", "responsibility", "harmony"], core: "Six emphasizes responsibility, care, beauty, belonging, and the desire to improve the environment for people who depend on one another.", strength: "At its best, 6 protects without smothering, takes responsibility without drama, and creates warmth through practical care.", challenge: "The shadow of 6 is perfectionism, rescuing people who did not ask to be rescued, or turning care into control.", love: "In relationships, 6 values loyalty, shared responsibility, emotional safety, and building a life that feels tended rather than merely occupied.", work: "At work, 6 suits service, leadership, education, health-adjacent support, hospitality, design, community work, and people management.", reflection: "What would responsible care look like without taking over?" },
  { value: 7, name: "The Seeker", keywords: ["analysis", "introspection", "discernment"], core: "Seven emphasizes investigation, privacy, pattern recognition, and the need to understand beneath the surface before committing to a conclusion.", strength: "At its best, 7 thinks independently, asks better questions, and notices distinctions that more hurried minds overlook.", challenge: "The shadow of 7 is withdrawal, cynicism, analysis paralysis, or treating emotional distance as the same thing as objectivity.", love: "In relationships, 7 needs trust, intellectual depth, personal space, and a partner who does not confuse quiet with indifference.", work: "At work, 7 favors research, analysis, technology, strategy, science, writing, specialist expertise, and complex problem solving.", reflection: "What becomes clearer if you stop seeking a quick answer?" },
  { value: 8, name: "The Executive", keywords: ["power", "results", "stewardship"], core: "Eight emphasizes material responsibility, ambition, leverage, and the consequences of how authority and resources are used.", strength: "At its best, 8 organizes people and resources effectively, thinks in outcomes, and accepts accountability for difficult decisions.", challenge: "The shadow of 8 is domination, status fixation, workaholism, or measuring every form of success in purely material terms.", love: "In relationships, 8 benefits from sharing power explicitly and remembering that competence is not a substitute for vulnerability.", work: "At work, 8 suits leadership, commercial strategy, finance, ownership, negotiation, operations, and roles with measurable responsibility.", reflection: "How can you use influence in a way you would respect if the roles were reversed?" },
  { value: 9, name: "The Humanitarian", keywords: ["completion", "compassion", "perspective"], core: "Nine emphasizes completion, broad perspective, generosity, and learning to release what has finished so energy can move somewhere useful.", strength: "At its best, 9 sees beyond narrow self-interest, integrates experience, and gives meaning to endings rather than treating them as failures.", challenge: "The shadow of 9 is martyrdom, vague idealism, difficulty letting go, or trying to save situations that have already run their course.", love: "In relationships, 9 seeks emotional breadth and meaning, but benefits from keeping compassion grounded in clear boundaries.", work: "At work, 9 fits education, creative work, public service, advocacy, international settings, counseling-adjacent roles, and mission-driven organizations.", reflection: "What is complete enough to release with dignity?" },
  { value: 11, name: "The Illuminator", keywords: ["intuition", "inspiration", "sensitivity"], core: "Eleven is treated in modern numerology as a master number that intensifies the receptive qualities of 2 with an emphasis on inspiration and heightened sensitivity.", strength: "At its best, 11 connects ideas, intuition, and communication in ways that help other people see a possibility more clearly.", challenge: "The shadow of 11 is nervous overextension, grandiosity, or treating every strong feeling as a special message that must be obeyed.", love: "In relationships, 11 benefits from emotional honesty, grounding routines, and partners who can respect sensitivity without feeding unnecessary drama.", work: "At work, 11 can suit creative direction, teaching, counseling-adjacent work, communication, innovation, and roles that translate abstract ideas into human terms.", reflection: "What inspired idea becomes useful once it is grounded in a practical next step?", master: true },
  { value: 22, name: "The Master Builder", keywords: ["vision", "execution", "scale"], core: "Twenty-two is treated as a master number combining the cooperative sensitivity of 2 with the constructive emphasis of 4, often framed as large-scale practical realization.", strength: "At its best, 22 turns ambitious ideas into systems, institutions, products, or structures that can function beyond one person's effort.", challenge: "The shadow of 22 is pressure, control, overreach, or becoming so attached to a grand plan that smaller workable steps are dismissed.", love: "In relationships, 22 needs room for ambition while remembering that shared life is built through ordinary reliability as much as large goals.", work: "At work, 22 suits institution-building, entrepreneurship, infrastructure, operations, transformation programs, and complex long-horizon projects.", reflection: "What large vision can be reduced to one credible piece of construction today?", master: true },
  { value: 33, name: "The Teacher", keywords: ["service", "compassion", "guidance"], core: "Thirty-three is treated as a master number that amplifies the expressive qualities of 3 and the caring responsibilities associated with 6.", strength: "At its best, 33 communicates care in a form that teaches, supports, or improves other people's capacity rather than keeping them dependent.", challenge: "The shadow of 33 is self-sacrifice, impossible standards, moral superiority, or assuming responsibility for everyone else's growth.", love: "In relationships, 33 benefits from mutual care, realistic expectations, and recognizing that devotion is healthiest when responsibility is shared.", work: "At work, 33 can suit teaching, mentoring, creative service, leadership, community-building, and roles where communication and stewardship overlap.", reflection: "Where can you help without making yourself responsible for another person's entire outcome?", master: true },
];

export const CORE_NUMBER_GUIDES: CoreNumberGuide[] = [
  { slug: "life-path", name: "Life Path Number", shortName: "Life Path", source: "Date of birth", meaning: "A broad birth-date number used in modern numerology to frame recurring themes, default tendencies, and the kinds of lessons a person may repeatedly encounter.", method: "Add the digits of the complete birth date and reduce the total, preserving 11, 22, or 33 when they appear as the final unreduced total." },
  { slug: "expression", name: "Expression / Destiny Number", shortName: "Expression", source: "All letters in the full name", meaning: "A name-based number commonly used to describe the style through which abilities, ambitions, and outward potential are expressed.", method: "Convert A–Z through the repeating 1–9 Pythagorean letter chart, total every letter, then reduce while preserving master numbers." },
  { slug: "soul-urge", name: "Soul Urge Number", shortName: "Soul Urge", source: "Vowels in the full name", meaning: "A modern numerology lens for inner motivation, private preference, and what tends to feel meaningful even when nobody else is watching.", method: "Use only A, E, I, O, and U from the normalized name, total their 1–9 values, then reduce. Oracle Mirror treats Y as a consonant for consistency." },
  { slug: "personality", name: "Personality Number", shortName: "Personality", source: "Consonants in the full name", meaning: "A name-based number used to reflect first impressions, visible style, and how a person may initially be read by others.", method: "Use consonants from the normalized name, total their 1–9 values, then reduce while preserving master numbers." },
  { slug: "birthday", name: "Birthday Number", shortName: "Birthday", source: "Day of the month of birth", meaning: "A compact number derived from the birth day alone, often interpreted as a particular talent, emphasis, or recurring style of action.", method: "Reduce the calendar day of birth to a single digit unless it is 11 or 22. A day cannot produce 33." },
  { slug: "personal-year", name: "Personal Year Number", shortName: "Personal Year", source: "Birth month + birth day + current calendar year", meaning: "A yearly cycle number used as a reflective theme for the current calendar year rather than as a fixed personality trait.", method: "Add the digits of the birth month and day to the digits of the selected calendar year, then reduce while preserving 11, 22, or 33." },
];

export function numerologyNumber(value: number): NumerologyNumber | undefined {
  return NUMEROLOGY_NUMBERS.find((item) => item.value === value);
}

export function coreNumberGuide(slug: string): CoreNumberGuide | undefined {
  return CORE_NUMBER_GUIDES.find((item) => item.slug === slug);
}
