export type PalmEntry={slug:string;name:string;icon:string;summary:string;tradition:string;reflection:string};

export const PALM_LINES:PalmEntry[]=[
{slug:"heart-line",name:"Heart Line",icon:"♡",summary:"In palmistry, the Heart Line is read symbolically for emotional style, attachment, affection, and how a person may approach intimacy.",tradition:"Readers usually begin beneath the little finger and follow the upper horizontal crease across the palm, considering depth, continuity, curve, branches, and where the line ends.",reflection:"Rather than asking whether a line predicts romance, use it as a prompt to notice how you communicate care, boundaries, and vulnerability."},
{slug:"head-line",name:"Head Line",icon:"⌁",summary:"The Head Line is traditionally associated with thinking style, concentration, imagination, judgement, and the balance between analysis and intuition.",tradition:"Palmists examine its length, slope, clarity, forks, and relationship to the Life Line. A straighter course is often interpreted as practical emphasis; a downward curve as imaginative emphasis.",reflection:"Treat the line as a reflective metaphor for how you solve problems, learn, and make decisions rather than as a neurological diagnosis."},
{slug:"life-line",name:"Life Line",icon:"◔",summary:"The Life Line curves around the base of the thumb and is traditionally read for vitality, pace, grounding, major transitions, and engagement with life—not lifespan.",tradition:"Modern responsible palmistry rejects the frightening claim that line length predicts age at death. Readers instead consider depth, arc, interruptions, sister lines, and branches as symbolic themes.",reflection:"Use the Life Line to reflect on energy management, stability, recovery, and the environments in which you feel most alive."},
{slug:"fate-line",name:"Fate Line",icon:"│",summary:"The Fate Line is a vertical palm line traditionally associated with vocation, structure, external obligations, and the degree to which life feels directed by circumstance or chosen purpose.",tradition:"Not everyone has a strong Fate Line. Its presence, absence, start point, breaks, and intersections are interpreted in many different schools and should never be treated as proof of destiny.",reflection:"Ask where your path is self-directed, where commitments shape it, and where changing course is possible."},
{slug:"sun-line",name:"Sun / Apollo Line",icon:"☀",summary:"The Sun Line, also called the Apollo Line, is traditionally linked with creative expression, recognition, satisfaction, and the wish to make work that feels personally meaningful.",tradition:"It is usually sought beneath the ring finger. Readers may consider whether it is clear, late-developing, branching, or absent; none of those features establishes future fame or wealth.",reflection:"Reflect on what kind of recognition actually matters to you and which activities create a sense of craft or fulfilment."},
{slug:"mercury-line",name:"Mercury / Health Line",icon:"☿",summary:"The Mercury Line has historically been given several meanings, including communication, business sense, nervous energy, and health symbolism.",tradition:"Older palmistry books often called it a Health Line, but palm creases cannot diagnose disease. Contemporary reflective use is better limited to communication, adaptability, and work habits.",reflection:"Use this line only as a symbolic prompt about communication and routines; seek qualified medical advice for health concerns."},
{slug:"girdle-of-venus",name:"Girdle of Venus",icon:"⌒",summary:"The Girdle of Venus is an arc above the Heart Line that some palmistry traditions associate with emotional sensitivity, intensity, aesthetic responsiveness, and strong reactions to atmosphere.",tradition:"It may appear complete, fragmented, faint, or not at all. Traditional interpretations vary substantially and should be treated as folklore rather than psychological measurement.",reflection:"Consider where sensitivity is a strength, where stimulation becomes tiring, and what helps you regulate emotional intensity."},
{slug:"relationship-lines",name:"Relationship Lines",icon:"═",summary:"Short horizontal lines at the edge of the palm below the little finger are often called relationship, union, or affection lines in palmistry.",tradition:"Popular books sometimes call them marriage lines, but they do not reliably count marriages, children, divorces, or relationship dates. Schools disagree heavily about their meaning.",reflection:"Use them as prompts to think about commitment, partnership expectations, and the difference between intimacy and social convention."},
{slug:"travel-lines",name:"Travel & Influence Lines",icon:"↗",summary:"Fine lines near the Mount of Moon or branching from larger lines are sometimes read as travel, movement, outside influence, or changes of environment.",tradition:"These interpretations are highly variable. A line cannot establish that a specific journey or relocation will occur.",reflection:"Reflect on your relationship with movement, curiosity, unfamiliar places, and the people or experiences that have changed your direction."}
];

export const HAND_SHAPES:PalmEntry[]=[
{slug:"earth-hand",name:"Earth Hand",icon:"◆",summary:"The Earth-hand archetype combines a relatively square palm with shorter fingers and is traditionally associated with practicality, steadiness, physical engagement, and preference for tangible results.",tradition:"Elemental hand typing is a modern interpretive convention that simplifies older chirognomic systems. Real hands rarely fit one category perfectly.",reflection:"Where do routine, craftsmanship, reliability, and direct experience help you thrive—and where can they become rigidity?"},
{slug:"air-hand",name:"Air Hand",icon:"◇",summary:"The Air-hand archetype generally describes a square or rectangular palm with longer fingers, symbolically linked to ideas, communication, curiosity, and mental movement.",tradition:"This is not a validated personality classification. Palmists use it as a broad symbolic starting point before considering proportions, fingers, lines, and context.",reflection:"Notice how information, conversation, novelty, and overthinking affect the way you make choices."},
{slug:"fire-hand",name:"Fire Hand",icon:"△",summary:"The Fire-hand archetype usually combines a longer palm with comparatively shorter fingers and is traditionally associated with initiative, enthusiasm, directness, and appetite for action.",tradition:"Traditional descriptions can become stereotypes; a hand shape cannot establish temperament or impulsivity scientifically.",reflection:"Where does decisive action create momentum for you, and where would patience or listening improve the result?"},
{slug:"water-hand",name:"Water Hand",icon:"▽",summary:"The Water-hand archetype is usually described as a long palm with long, often slender fingers and is symbolically associated with receptivity, imagination, sensitivity, and emotional nuance.",tradition:"Elemental labels are interpretive metaphors, not biometric personality tests. Mixed proportions are normal.",reflection:"Consider how intuition, empathy, boundaries, and recovery time interact in your daily life."}
];

export const PALM_MOUNTS:PalmEntry[]=[
{slug:"jupiter",name:"Mount of Jupiter",icon:"♃",summary:"The Mount of Jupiter lies below the index finger and is traditionally linked with ambition, confidence, leadership, ideals, and the desire to grow.",tradition:"Palmists compare relative fullness and markings rather than treating a single feature in isolation.",reflection:"What kind of leadership or growth feels meaningful rather than merely impressive?"},
{slug:"saturn",name:"Mount of Saturn",icon:"♄",summary:"The Mount of Saturn beneath the middle finger is traditionally associated with responsibility, seriousness, patience, limits, and contemplation.",tradition:"An emphasized or quiet mount is interpreted differently across schools; neither is a diagnosis of mood or personality.",reflection:"Where do discipline and realism serve you, and where could they become unnecessary heaviness?"},
{slug:"apollo",name:"Mount of Apollo",icon:"☉",summary:"The Mount of Apollo beneath the ring finger is traditionally associated with creativity, visibility, pleasure, aesthetics, confidence, and appreciation of craft.",tradition:"It is often read together with the Sun Line and ring finger rather than as a standalone promise of talent or fame.",reflection:"What do you create or appreciate for its own sake, even when nobody applauds?"},
{slug:"mercury",name:"Mount of Mercury",icon:"☿",summary:"The Mount of Mercury beneath the little finger is symbolically associated with communication, trade, improvisation, wit, and practical intelligence.",tradition:"Historical palmists sometimes attached health claims to this area; Oracle Mirror does not use palm features to diagnose health.",reflection:"How clearly do you exchange ideas, negotiate, explain, listen, and adapt?"},
{slug:"venus",name:"Mount of Venus",icon:"♀",summary:"The Mount of Venus is the padded area at the base of the thumb and is traditionally associated with warmth, affection, sensuality, sociability, and vitality.",tradition:"Its relative size varies naturally with anatomy and body composition, so symbolic readings should not be confused with medical assessment.",reflection:"What nourishes connection, pleasure, generosity, and healthy boundaries in your life?"},
{slug:"moon",name:"Mount of Moon / Luna",icon:"☾",summary:"The Mount of Moon lies along the outer lower palm and is traditionally associated with imagination, intuition, travel, dreams, receptivity, and inner life.",tradition:"Readers often consider its relation to travel/influence lines and the slope of the Head Line, but schools vary widely.",reflection:"Where do imagination and intuition help you, and where do they need grounding in evidence or action?"},
{slug:"mars",name:"Mounts of Mars",icon:"♂",summary:"Palmistry often describes inner and outer Mars areas plus the Plain of Mars, symbolically connected with courage, endurance, conflict style, self-protection, and resilience.",tradition:"Different schools divide Mars territory differently. These zones do not measure aggression, trauma, or physical strength scientifically.",reflection:"How do you respond to pressure: advance, defend, negotiate, endure, or withdraw—and which response best fits the situation?"}
];

export const PALM_DIGITS:PalmEntry[]=[
{slug:"index-finger",name:"Index / Jupiter Finger",icon:"☝",summary:"The index finger is traditionally linked with Jupiter themes such as aspiration, authority, standards, and self-direction.",tradition:"Palmists compare its length and set with neighbouring fingers and the Jupiter mount, but proportions are naturally variable.",reflection:"How do you define success, and when does healthy ambition become comparison?"},
{slug:"middle-finger",name:"Middle / Saturn Finger",icon:"│",summary:"The middle finger is traditionally associated with Saturn themes: responsibility, boundaries, structure, realism, and consequence.",tradition:"It is normally the longest finger; small proportional differences are not reliable measures of character.",reflection:"Which responsibilities deserve your seriousness, and which burdens could be renegotiated?"},
{slug:"ring-finger",name:"Ring / Apollo Finger",icon:"☀",summary:"The ring finger is traditionally connected with Apollo themes such as creativity, performance, taste, visibility, and willingness to take expressive risks.",tradition:"Finger-length claims are frequently overstated online. Palmistry uses them symbolically and Oracle Mirror does not infer hormones, sexuality, intelligence, or medical traits from them.",reflection:"Where are you willing to be seen for something you genuinely value?"},
{slug:"little-finger",name:"Little / Mercury Finger",icon:"☿",summary:"The little finger is traditionally associated with Mercury themes: communication, negotiation, humour, adaptability, and social intelligence.",tradition:"Its length, set, and flexibility are interpreted differently across palmistry schools and are not validated personality metrics.",reflection:"Where would clearer language, better listening, or a more direct conversation improve matters?"},
{slug:"thumb",name:"Thumb",icon:"◖",summary:"The thumb is given unusual importance in many palmistry systems because its angle, flexibility, phalanges, and Venus mount are read symbolically for will, reasoning, openness, and self-direction.",tradition:"Anatomy, joint mobility, injury, and genetics strongly affect thumb appearance, so deterministic character claims are inappropriate.",reflection:"How do determination and flexibility balance in the way you pursue goals?"},
{slug:"finger-spacing",name:"Finger Spacing & Set",icon:"⋮",summary:"Palmists sometimes use the natural spacing and set of the fingers as a symbolic lens on independence, caution, sociability, and comfort with convention.",tradition:"Hand posture changes with tension, habit, temperature, and instruction, so a single posed photograph is especially poor evidence for fixed personality claims.",reflection:"Where do you prefer autonomy, where do you seek coordination, and how consciously are you choosing between them?"}
];

export const PALM_MARKINGS:PalmEntry[]=[
{slug:"forks",name:"Forks",icon:"Y",summary:"A fork is a line that divides into two branches. Palmists often interpret it as diversification, dual direction, or the need to integrate two tendencies.",tradition:"Meaning depends heavily on which line is involved and the direction of the branches; there is no universal fork prediction.",reflection:"Where are two valid paths or perspectives asking to be integrated?"},
{slug:"breaks",name:"Breaks",icon:"— —",summary:"A visible interruption in a major line is traditionally read as a change of pattern, transition, interruption, or redirection rather than an automatic disaster.",tradition:"Older fatalistic readings can be needlessly alarming. Crease patterns vary naturally and change in appearance with hand position and skin condition.",reflection:"Which transitions in your life changed the way you operate, and what continuity remained underneath?"},
{slug:"islands",name:"Islands",icon:"◇",summary:"An island is a small enclosed or split section along a line, traditionally associated with diffusion, complication, divided attention, or a period of reduced clarity.",tradition:"It should not be used to diagnose illness, infertility, mental health conditions, or specific future crises.",reflection:"Where is attention currently scattered, and what would simplify the situation?"},
{slug:"crosses",name:"Crosses",icon:"×",summary:"Cross-shaped intersections are often treated as emphasis points in palmistry and interpreted according to the line or mount where they occur.",tradition:"Different traditions assign conflicting meanings to crosses, including both challenge and spiritual significance.",reflection:"What issue keeps intersecting with other priorities and deserves deliberate attention?"},
{slug:"stars",name:"Stars",icon:"✦",summary:"A cluster of short lines forming a star is traditionally read as concentrated emphasis, sudden visibility, disruption, or a striking turning point depending on location.",tradition:"Star interpretations vary dramatically and should never be used to predict accidents, fame, or catastrophe as certainties.",reflection:"Where is intensity building, and how can you direct it constructively?"},
{slug:"squares",name:"Squares",icon:"□",summary:"Squares are traditionally described as protective or containing symbols, suggesting boundaries, stabilization, or recovery around the feature they enclose.",tradition:"This is symbolic folklore, not evidence that a person is physically protected from harm.",reflection:"What boundary, structure, or support system could make a difficult situation safer to navigate?"},
{slug:"triangles",name:"Triangles",icon:"△",summary:"Triangles formed by intersecting lines are traditionally associated with focus, skill, synthesis, or concentrated learning, depending on where they appear.",tradition:"Because tiny intersecting creases are common, readers should avoid forcing every shape into a meaningful symbol.",reflection:"Where are several skills or insights converging into something useful?"},
{slug:"grilles",name:"Grilles & Crosshatching",icon:"#",summary:"Dense crosshatching on a mount is traditionally interpreted as dispersed energy, complexity, competing demands, or overuse of that mount's symbolic theme.",tradition:"Skin texture and fine creasing vary with age, work, hydration, and anatomy, so symbolic readings must remain modest.",reflection:"Where are too many demands competing for the same resource or attention?"}
];

export const PALM_GUIDES=[
{slug:"how-to-read-palm",name:"How to Read a Palm",summary:"A responsible palm reading starts with observation before interpretation: hand shape, major lines, mounts, digits, and markings are considered together rather than turning one crease into a dramatic prediction."},
{slug:"left-right-hands",name:"Left Hand vs Right Hand",summary:"Palmistry traditions disagree about which hand represents inherited tendencies, lived expression, dominant behaviour, or present development. A practical modern approach compares both hands and avoids rigid gender rules."},
{slug:"history",name:"History of Palmistry",summary:"Palm-reading traditions developed across multiple cultures and were systematized in different ways. European chiromancy is documented in medieval and early-modern sources, while modern popular palmistry was heavily shaped by nineteenth-century writers."},
{slug:"science",name:"Palmistry and Science",summary:"Palmistry is an interpretive divination tradition, not a scientifically validated method for predicting events or measuring personality. Dermatoglyphics, by contrast, is the scientific study of friction-ridge patterns such as fingerprints."},
{slug:"ethics",name:"Ethical Palm Reading",summary:"Good palm-reading practice avoids fear, medical diagnosis, guaranteed predictions, coercion, and claims that a crease fixes someone's fate. Symbolic interpretation is most constructive when it supports reflection and personal agency."}
] as const;

export const palmEntryBySlug=(items:readonly PalmEntry[],slug:string)=>items.find(x=>x.slug===slug);
