export type Rune = {
  slug: string;
  name: string;
  glyph: string;
  sound: string;
  keywords: string[];
  core: string;
  light: string;
  challenge: string;
  reflection: string;
};

export const ELDER_FUTHARK: Rune[] = [
  { slug: "fehu", name: "Fehu", glyph: "ᚠ", sound: "f", keywords: ["wealth", "resources", "movement"], core: "Fehu points to resources in motion: money, skill, energy, time, or support that becomes useful when circulated wisely.", light: "Notice what is already available and put it to purposeful use rather than merely collecting it.", challenge: "Possession can become anxiety when holding on matters more than using what you have well.", reflection: "What resource can you put into motion today?" },
  { slug: "uruz", name: "Uruz", glyph: "ᚢ", sound: "u", keywords: ["strength", "vitality", "endurance"], core: "Uruz evokes raw strength, vitality, resilience, and the capacity to meet a demanding phase with grounded effort.", light: "Choose the action that builds capacity instead of the shortcut that only feels powerful for a moment.", challenge: "Force without direction can become stubbornness, exhaustion, or unnecessary conflict.", reflection: "Where would steady strength serve you better than urgency?" },
  { slug: "thurisaz", name: "Thurisaz", glyph: "ᚦ", sound: "th", keywords: ["boundary", "friction", "defense"], core: "Thurisaz marks a threshold where friction, defense, or a sharp interruption asks you to become more deliberate.", light: "A clear boundary or well-timed pause can protect what matters and prevent a rash move.", challenge: "Reacting from irritation can turn a useful warning into needless escalation.", reflection: "What deserves a pause before you respond?" },
  { slug: "ansuz", name: "Ansuz", glyph: "ᚨ", sound: "a", keywords: ["communication", "insight", "message"], core: "Ansuz centers on language, listening, learning, and the message that becomes visible when communication is handled carefully.", light: "Ask the better question, listen for what is actually being said, and make your own meaning precise.", challenge: "Noise, assumption, flattery, or clever wording can disguise weak understanding.", reflection: "What conversation needs clearer words or better listening?" },
  { slug: "raidho", name: "Raidho", glyph: "ᚱ", sound: "r", keywords: ["journey", "rhythm", "direction"], core: "Raidho suggests movement with structure: a journey, process, routine, or sequence that works when each step supports the next.", light: "Align the route with the destination and let good rhythm carry more of the load.", challenge: "Motion without direction can look productive while taking you farther from the point.", reflection: "Is your current route actually leading where you want to go?" },
  { slug: "kenaz", name: "Kenaz", glyph: "ᚲ", sound: "k", keywords: ["torch", "clarity", "craft"], core: "Kenaz is the torch: illumination through craft, practice, curiosity, and the moment a confusing pattern becomes understandable.", light: "Bring light to one small area and work it carefully; clarity often expands from there.", challenge: "Knowing more is not the same as acting wisely, and excessive analysis can burn time without creating movement.", reflection: "What would become easier if you understood it one level more deeply?" },
  { slug: "gebo", name: "Gebo", glyph: "ᚷ", sound: "g", keywords: ["gift", "exchange", "reciprocity"], core: "Gebo concerns gifts, exchange, reciprocity, agreements, and the balance created when giving and receiving remain voluntary and meaningful.", light: "Look for the exchange where both sides gain dignity, value, or trust.", challenge: "A gift with hidden strings is not really a gift; imbalance can quietly become resentment.", reflection: "Where could a fairer exchange strengthen a relationship?" },
  { slug: "wunjo", name: "Wunjo", glyph: "ᚹ", sound: "w", keywords: ["joy", "harmony", "belonging"], core: "Wunjo points toward joy, harmony, belonging, and the relief that appears when people, values, and circumstances briefly come into alignment.", light: "Let a genuine success be enjoyed and shared instead of immediately turning it into the next task.", challenge: "Comfort can become avoidance if harmony is preserved by refusing to address what matters.", reflection: "What is already going well enough to appreciate?" },
  { slug: "hagalaz", name: "Hagalaz", glyph: "ᚺ", sound: "h", keywords: ["disruption", "weather", "reset"], core: "Hagalaz represents disruptive weather: conditions you cannot fully control that break a pattern and force adaptation.", light: "Protect what is essential, release what cannot be controlled, and look for the new shape that becomes possible afterward.", challenge: "Fighting every uncontrollable variable can waste the energy needed for recovery and rebuilding.", reflection: "What can you stabilize even if you cannot control the whole situation?" },
  { slug: "nauthiz", name: "Nauthiz", glyph: "ᚾ", sound: "n", keywords: ["need", "constraint", "patience"], core: "Nauthiz highlights need, constraint, scarcity, and the discipline of working honestly with limits rather than pretending they are not there.", light: "A constraint can clarify priorities and reveal what is genuinely necessary.", challenge: "Frustration grows when desire is treated as entitlement or when every limitation is read as failure.", reflection: "What is truly necessary here, and what is merely preferred?" },
  { slug: "isa", name: "Isa", glyph: "ᛁ", sound: "i", keywords: ["stillness", "pause", "focus"], core: "Isa is ice: stillness, concentration, delay, and the value of stopping motion long enough to see what movement was hiding.", light: "Use the pause to simplify, observe, and protect energy until conditions change.", challenge: "Stillness becomes stagnation when a temporary pause turns into fear of moving again.", reflection: "What becomes visible when you stop pushing for a moment?" },
  { slug: "jera", name: "Jera", glyph: "ᛃ", sound: "y/j", keywords: ["harvest", "cycle", "timing"], core: "Jera concerns harvest, seasonal timing, cause and effect, and results that arrive through repeated effort rather than instant transformation.", light: "Keep tending the process; some outcomes need the full cycle before they can be judged fairly.", challenge: "Impatience can make you abandon work just before it begins to compound.", reflection: "What process deserves another season of consistent attention?" },
  { slug: "eihwaz", name: "Eihwaz", glyph: "ᛇ", sound: "ï/ei", keywords: ["endurance", "axis", "transition"], core: "Eihwaz is associated in modern rune practice with endurance, inner structure, and transitions that require steadiness between an old state and a new one.", light: "Hold your center while the surrounding form changes; not every transition needs to be rushed.", challenge: "Rigidity can masquerade as resilience when adaptation is actually required.", reflection: "What principle should remain steady while everything else changes?" },
  { slug: "perthro", name: "Perthro", glyph: "ᛈ", sound: "p", keywords: ["mystery", "chance", "unknown"], core: "Perthro is commonly read today as mystery, chance, hidden factors, and the part of a situation that cannot yet be known with confidence.", light: "Leave room for surprise and make decisions that remain workable across more than one possible outcome.", challenge: "Trying to force certainty from incomplete information can create false confidence.", reflection: "What decision would improve if you allowed for the unknown?" },
  { slug: "algiz", name: "Algiz", glyph: "ᛉ", sound: "z/ʀ", keywords: ["protection", "awareness", "support"], core: "Algiz is widely used in modern rune symbolism for protection, alertness, support, and the instinct to preserve a healthy boundary.", light: "Strengthen the safeguards that let you stay open without becoming careless.", challenge: "Defensiveness can isolate you if every uncertainty is treated as a threat.", reflection: "What boundary would help you feel safer without closing you off?" },
  { slug: "sowilo", name: "Sowilo", glyph: "ᛋ", sound: "s", keywords: ["sun", "clarity", "success"], core: "Sowilo evokes the sun: visibility, confidence, direction, and the energizing effect of seeing a path clearly enough to commit to it.", light: "Put energy behind the direction that remains coherent when viewed in full daylight.", challenge: "Confidence becomes blinding when success is assumed to prove that every judgment is correct.", reflection: "What becomes obvious when you strip away unnecessary doubt?" },
  { slug: "tiwaz", name: "Tiwaz", glyph: "ᛏ", sound: "t", keywords: ["justice", "courage", "principle"], core: "Tiwaz points to courage guided by principle: fairness, duty, sacrifice, and choosing the standard you are willing to be measured against.", light: "Let principle simplify the decision, especially where convenience and integrity pull in different directions.", challenge: "Self-righteousness can turn principle into a weapon instead of a guide.", reflection: "What choice would you make if fairness mattered more than convenience?" },
  { slug: "berkano", name: "Berkano", glyph: "ᛒ", sound: "b", keywords: ["growth", "nurture", "beginning"], core: "Berkano suggests growth through nurture: beginnings, recovery, care, and creating the conditions in which something young can become resilient.", light: "Protect the early stage and give it enough structure, patience, and care to develop naturally.", challenge: "Overprotecting a beginning can prevent it from becoming strong enough to stand on its own.", reflection: "What new thing needs care rather than pressure?" },
  { slug: "ehwaz", name: "Ehwaz", glyph: "ᛖ", sound: "e", keywords: ["partnership", "movement", "trust"], core: "Ehwaz centers on coordinated movement, partnership, trust, and progress created by two forces learning to work in rhythm.", light: "Progress may come faster through cooperation than through increasing your individual effort.", challenge: "A partnership stalls when roles, pace, or expectations remain unspoken.", reflection: "Who or what needs better coordination with you?" },
  { slug: "mannaz", name: "Mannaz", glyph: "ᛗ", sound: "m", keywords: ["humanity", "self", "community"], core: "Mannaz reflects the human self in community: identity, intelligence, cooperation, perspective, and the ways other people help reveal who we are.", light: "Use both self-knowledge and outside perspective; neither is complete on its own.", challenge: "Ego can distort feedback, while conformity can erase useful individuality.", reflection: "What are other people showing you about yourself right now?" },
  { slug: "laguz", name: "Laguz", glyph: "ᛚ", sound: "l", keywords: ["water", "intuition", "flow"], core: "Laguz evokes water: intuition, emotion, adaptation, depth, and the intelligence of moving with conditions without losing direction.", light: "Allow information from feeling and instinct into the decision, then test it against reality.", challenge: "Going with the flow can become drift when no direction or boundary remains.", reflection: "Where could you adapt without abandoning your purpose?" },
  { slug: "ingwaz", name: "Ingwaz", glyph: "ᛜ", sound: "ng", keywords: ["potential", "gestation", "completion"], core: "Ingwaz is often associated with contained potential, gestation, consolidation, and the quiet stage before something is ready to emerge.", light: "Finish gathering energy and complete what needs completion before forcing the next launch.", challenge: "Potential becomes pressure if it is stored indefinitely and never given a form.", reflection: "What is nearly ready, but still needs one final stage of preparation?" },
  { slug: "dagaz", name: "Dagaz", glyph: "ᛞ", sound: "d", keywords: ["daybreak", "breakthrough", "change"], core: "Dagaz represents daybreak: a shift in perspective, breakthrough, or transition where the situation can suddenly be seen in a different light.", light: "Act on the clearer view while remaining aware that every new day still requires practical work.", challenge: "A breakthrough can be wasted if insight is mistaken for finished execution.", reflection: "What changes if you look at the problem from the opposite side?" },
  { slug: "othala", name: "Othala", glyph: "ᛟ", sound: "o", keywords: ["heritage", "home", "inheritance"], core: "Othala concerns inheritance in the broad sense: home, heritage, belonging, accumulated knowledge, and what is received from those who came before.", light: "Choose consciously which parts of your inheritance deserve to be protected, improved, and passed forward.", challenge: "Tradition can become exclusion or stagnation when inherited patterns are treated as automatically correct.", reflection: "What have you inherited that you want to preserve—and what should change?" },
];

export const RUNE_BY_SLUG = new Map(ELDER_FUTHARK.map((rune) => [rune.slug, rune]));

export function runeBySlug(slug: string): Rune | undefined {
  return RUNE_BY_SLUG.get(slug.toLowerCase());
}
