export type TarotArcana = "major" | "minor";
export type TarotSuit = "Wands" | "Cups" | "Swords" | "Pentacles" | null;

export type TarotCard = {
  id: number;
  slug: string;
  name: string;
  arcana: TarotArcana;
  suit: TarotSuit;
  rank: string;
  glyph: string;
  keywords: string[];
  upright: string;
  reversed: string;
  love: string;
  work: string;
  reflection: string;
};

const MAJOR: TarotCard[] = [
  { id: 0, slug: "the-fool", name: "The Fool", arcana: "major", suit: null, rank: "0", glyph: "✧", keywords: ["beginnings", "freedom", "curiosity"], upright: "A new path opens before certainty has arrived. The Fool favors experimentation, openness, and a willingness to learn by moving.", reversed: "The adventurous impulse may be turning into avoidance, poor preparation, or fear disguised as endless hesitation.", love: "Fresh energy, vulnerability, or an unconventional connection can matter more than trying to control the outcome.", work: "A new role, idea, or direction deserves exploration, but enthusiasm works best when paired with basic preparation.", reflection: "Where would curiosity serve you better than certainty?" },
  { id: 1, slug: "the-magician", name: "The Magician", arcana: "major", suit: null, rank: "I", glyph: "✦", keywords: ["skill", "initiative", "agency"], upright: "Resources, timing, and personal agency are ready to be brought together. The Magician asks you to use what is already available with focus.", reversed: "Talent may be scattered, underused, or directed toward appearance rather than substance.", love: "Clear intention and honest communication can move a connection forward more effectively than hints or performance.", work: "You likely have enough tools to begin; execution and coordination now matter more than collecting more options.", reflection: "What can you create with the tools already in your hands?" },
  { id: 2, slug: "the-high-priestess", name: "The High Priestess", arcana: "major", suit: null, rank: "II", glyph: "☾", keywords: ["intuition", "silence", "inner knowledge"], upright: "Not every answer improves when forced. The High Priestess favors observation, pattern recognition, and allowing quieter information to surface.", reversed: "Intuition may be clouded by projection, secrecy, or the urge to call anxiety a message.", love: "Pay attention to what is felt but also verify assumptions; mystery is not the same as certainty.", work: "Research, listening, and discretion may be more valuable than making the next move too quickly.", reflection: "What becomes clearer when you stop trying to force an answer?" },
  { id: 3, slug: "the-empress", name: "The Empress", arcana: "major", suit: null, rank: "III", glyph: "❀", keywords: ["nurture", "abundance", "creativity"], upright: "Growth responds to care. The Empress emphasizes creativity, nourishment, beauty, and the patient work of helping something flourish.", reversed: "Overgiving, neglecting yourself, or smothering a developing situation may be draining the very growth you want.", love: "Warmth and generosity deepen connection when they remain mutual rather than self-erasing.", work: "A project can grow through patient cultivation, good presentation, and attention to the people around it.", reflection: "What would grow if you gave it consistent care rather than pressure?" },
  { id: 4, slug: "the-emperor", name: "The Emperor", arcana: "major", suit: null, rank: "IV", glyph: "♜", keywords: ["structure", "authority", "boundaries"], upright: "Structure creates room for progress. The Emperor favors clear standards, responsibility, and decisions that can survive pressure.", reversed: "Control may be becoming rigidity, domination, or resistance to useful change.", love: "Healthy boundaries and reliability matter more than trying to manage another person's feelings.", work: "Define roles, rules, and priorities; disciplined structure can remove avoidable chaos.", reflection: "What boundary or structure would make this situation easier to navigate?" },
  { id: 5, slug: "the-hierophant", name: "The Hierophant", arcana: "major", suit: null, rank: "V", glyph: "⚜", keywords: ["tradition", "learning", "values"], upright: "A tested framework, mentor, institution, or shared value system can provide useful direction.", reversed: "Tradition may be followed automatically even though the situation now requires independent judgment.", love: "Shared values and expectations deserve explicit discussion rather than assumption.", work: "Established methods, formal training, or expert advice may save unnecessary reinvention.", reflection: "Which tradition deserves respect, and which one deserves examination?" },
  { id: 6, slug: "the-lovers", name: "The Lovers", arcana: "major", suit: null, rank: "VI", glyph: "♡", keywords: ["choice", "union", "values"], upright: "The Lovers concerns alignment as much as romance: a meaningful choice becomes clearer when values and desire point in the same direction.", reversed: "Attraction, convenience, or pressure may be pulling against your deeper values.", love: "Mutual choice, honesty, and compatibility matter more than intensity alone.", work: "A partnership or major decision should be tested against long-term values, not only short-term appeal.", reflection: "What choice would feel most aligned with who you want to be?" },
  { id: 7, slug: "the-chariot", name: "The Chariot", arcana: "major", suit: null, rank: "VII", glyph: "✹", keywords: ["direction", "discipline", "momentum"], upright: "Momentum becomes useful when competing impulses are pulled into one direction. The Chariot favors focus and deliberate movement.", reversed: "Speed without alignment can create drift, conflict, or burnout.", love: "Forward movement works when both people understand where the relationship is actually going.", work: "Choose a direction and coordinate your energy around it instead of trying to win every battle at once.", reflection: "What deserves your full direction rather than divided effort?" },
  { id: 8, slug: "strength", name: "Strength", arcana: "major", suit: null, rank: "VIII", glyph: "∞", keywords: ["courage", "patience", "self-command"], upright: "Strength is controlled power: patience, courage, compassion, and the ability to stay steady without becoming passive.", reversed: "Self-doubt, suppressed anger, or exhaustion may be making every challenge feel larger than it is.", love: "Gentle honesty and emotional steadiness can be more influential than force or dramatic gestures.", work: "Resilience, diplomacy, and calm persistence are likely to outperform confrontation.", reflection: "Where can calm strength do what force cannot?" },
  { id: 9, slug: "the-hermit", name: "The Hermit", arcana: "major", suit: null, rank: "IX", glyph: "⌁", keywords: ["solitude", "wisdom", "reflection"], upright: "A quieter pace creates room for insight. The Hermit favors reflection, independence, and finding a guiding principle before rejoining the noise.", reversed: "Useful solitude may be becoming isolation, overthinking, or reluctance to re-engage.", love: "Space can clarify feelings, but prolonged withdrawal should not replace communication.", work: "Independent analysis, study, or stepping away from group noise can reveal the better path.", reflection: "What do you know when nobody else is telling you what to think?" },
  { id: 10, slug: "wheel-of-fortune", name: "Wheel of Fortune", arcana: "major", suit: null, rank: "X", glyph: "◉", keywords: ["cycles", "change", "timing"], upright: "Conditions are shifting. The Wheel emphasizes cycles, timing, and the value of responding intelligently to forces larger than personal preference.", reversed: "Resistance to change may be increasing frustration, or a repeating pattern may need to be interrupted consciously.", love: "A relationship may be entering a new phase; adaptability matters more than trying to recreate an earlier one.", work: "External conditions may change quickly, so flexibility and contingency planning are valuable.", reflection: "What changes if you work with the cycle instead of against it?" },
  { id: 11, slug: "justice", name: "Justice", arcana: "major", suit: null, rank: "XI", glyph: "⚖", keywords: ["fairness", "truth", "consequence"], upright: "Justice asks for clear-eyed assessment, accountability, and choices you can defend when emotion settles.", reversed: "Bias, avoidance, or an uneven standard may be distorting the decision.", love: "Reciprocity and honest accountability are more important than keeping score.", work: "Contracts, evidence, process, and fair standards deserve close attention.", reflection: "What would a fair-minded observer say matters most here?" },
  { id: 12, slug: "the-hanged-man", name: "The Hanged Man", arcana: "major", suit: null, rank: "XII", glyph: "⟲", keywords: ["pause", "perspective", "surrender"], upright: "Progress may require a pause, changed viewpoint, or willingness to stop forcing the old approach.", reversed: "Delay may be continuing without producing insight, or sacrifice may have become habitual rather than purposeful.", love: "A different perspective can soften a stalemate, but indefinite waiting is not the same as patience.", work: "Stop pushing long enough to examine whether the current method is the real obstacle.", reflection: "What becomes possible if you look at this from the opposite angle?" },
  { id: 13, slug: "death", name: "Death", arcana: "major", suit: null, rank: "XIII", glyph: "✢", keywords: ["ending", "transition", "release"], upright: "An old form is ending so that energy can move elsewhere. Death is about transition, not literal death.", reversed: "Holding on to what has already finished may be prolonging discomfort and blocking renewal.", love: "A relationship pattern may need to end even if the relationship itself continues.", work: "A role, process, or professional identity may have reached the end of its useful life.", reflection: "What are you ready to stop carrying into the next chapter?" },
  { id: 14, slug: "temperance", name: "Temperance", arcana: "major", suit: null, rank: "XIV", glyph: "⚗", keywords: ["balance", "integration", "moderation"], upright: "Temperance favors blending, pacing, and finding the workable middle path between extremes.", reversed: "Excess, impatience, or competing priorities may be preventing a stable rhythm.", love: "A durable connection benefits from mutual adjustment rather than one person doing all the adapting.", work: "Combine strengths, simplify competing priorities, and favor sustainable pace over dramatic bursts.", reflection: "What two things could work better together than apart?" },
  { id: 15, slug: "the-devil", name: "The Devil", arcana: "major", suit: null, rank: "XV", glyph: "⛓", keywords: ["attachment", "temptation", "constraint"], upright: "The Devil highlights attachment, compulsion, and bargains that feel rewarding while narrowing your freedom.", reversed: "A pattern may be ready to loosen once you stop treating it as inevitable.", love: "Intensity is not the same as health; notice where desire, jealousy, dependence, or control is setting the terms.", work: "Golden handcuffs, status, fear, or short-term reward may be keeping you in a limiting pattern.", reflection: "What has power over you mainly because you keep agreeing that it does?" },
  { id: 16, slug: "the-tower", name: "The Tower", arcana: "major", suit: null, rank: "XVI", glyph: "⚡", keywords: ["disruption", "revelation", "reset"], upright: "A structure built on weak assumptions may be breaking open. The Tower is disruptive, but it can expose what was already unstable.", reversed: "You may be delaying an unavoidable change or experiencing a quieter internal version of the same reckoning.", love: "A difficult truth can clear away a false story and force more honest terms.", work: "Plans may need rapid revision when a foundational assumption changes.", reflection: "What truth becomes useful once the initial shock has passed?" },
  { id: 17, slug: "the-star", name: "The Star", arcana: "major", suit: null, rank: "XVII", glyph: "★", keywords: ["hope", "renewal", "guidance"], upright: "The Star brings renewal, proportion, and a reason to continue after difficulty. Hope becomes practical when it guides the next small action.", reversed: "Discouragement or comparison may be obscuring evidence that recovery is already happening.", love: "Honesty and gentleness can restore trust where pressure would only deepen distance.", work: "A clearer long-term vision can help you move beyond a recent setback or period of uncertainty.", reflection: "What small sign suggests that renewal is already underway?" },
  { id: 18, slug: "the-moon", name: "The Moon", arcana: "major", suit: null, rank: "XVIII", glyph: "☽", keywords: ["uncertainty", "imagination", "subconscious"], upright: "The Moon marks incomplete information, strong feeling, imagination, and a landscape where intuition should be tested rather than blindly obeyed.", reversed: "Confusion may be beginning to clear, or fear may be exposed as larger than the evidence supports.", love: "Avoid filling gaps with assumptions; ask what is true before deciding what a silence means.", work: "Verify information, document details, and distinguish creative intuition from unsupported certainty.", reflection: "Which part of this situation is fact, and which part is projection?" },
  { id: 19, slug: "the-sun", name: "The Sun", arcana: "major", suit: null, rank: "XIX", glyph: "☀", keywords: ["clarity", "vitality", "success"], upright: "Visibility, confidence, and uncomplicated energy are increasing. The Sun favors openness, celebration, and clear action.", reversed: "A positive situation may be delayed, understated, or overshadowed by unrealistic expectations of perfection.", love: "Warmth, directness, and shared enjoyment can strengthen the connection.", work: "Recognition and momentum are available when you communicate clearly and let good work be visible.", reflection: "What is already going well enough to acknowledge openly?" },
  { id: 20, slug: "judgement", name: "Judgement", arcana: "major", suit: null, rank: "XX", glyph: "↟", keywords: ["reckoning", "calling", "renewal"], upright: "Judgement asks you to integrate the past, answer what now feels important, and make a decision from a more mature viewpoint.", reversed: "Old shame, fear of evaluation, or refusal to decide may be keeping you in an expired version of yourself.", love: "A relationship can move forward when past lessons are acknowledged without endlessly retrying the old argument.", work: "A significant review, decision, or change in vocation may deserve serious attention.", reflection: "What lesson from the past is ready to become a decision now?" },
  { id: 21, slug: "the-world", name: "The World", arcana: "major", suit: null, rank: "XXI", glyph: "◎", keywords: ["completion", "integration", "achievement"], upright: "A cycle reaches meaningful completion. The World favors integration, perspective, and acknowledging how far the journey has actually come.", reversed: "A final loose end, unfinished lesson, or reluctance to close the chapter may be delaying completion.", love: "A relationship may be entering a mature new phase once unfinished business is addressed.", work: "Completion, launch, graduation, or recognition is close enough that finishing well matters more than starting something new.", reflection: "What deserves to be completed properly before the next cycle begins?" },
];

const SUITS = {
  Wands: { glyph: "♨", theme: "initiative, creativity, ambition, and the use of personal energy", love: "chemistry, pursuit, spontaneity, and the energy being invested in connection", work: "ambition, enterprise, momentum, leadership, and creative execution" },
  Cups: { glyph: "☕", theme: "emotion, relationship, imagination, intuition, and what creates a sense of connection", love: "emotional availability, affection, intimacy, and the quality of mutual feeling", work: "team chemistry, meaningful work, creativity, and emotional investment" },
  Swords: { glyph: "⚔", theme: "thought, communication, conflict, decision-making, and the stories the mind builds", love: "communication, boundaries, truth, tension, and the assumptions shaping the relationship", work: "analysis, strategy, negotiation, decisions, and intellectual pressure" },
  Pentacles: { glyph: "◈", theme: "resources, work, health routines, stability, craft, and the material side of life", love: "reliability, practical support, shared resources, and what makes a bond sustainable", work: "money, skills, operations, long-term value, and practical progress" },
} as const;

const RANKS = [
  ["Ace", "a concentrated beginning and raw potential", "Potential may exist without a clear channel, or enthusiasm may be blocked before it becomes action."],
  ["Two", "choice, balance, and the first attempt to hold two forces at once", "Indecision, imbalance, or trying to preserve incompatible options may be creating strain."],
  ["Three", "growth through participation, early results, and movement beyond the individual", "Coordination may be weak, support may be missing, or an early success may not yet be stable."],
  ["Four", "structure, consolidation, boundaries, and a temporary point of stability", "Stability may be becoming stagnation, defensiveness, or fear of changing what currently works."],
  ["Five", "friction, challenge, comparison, and the instability that exposes weak points", "Conflict may be avoided rather than resolved, or the struggle may be consuming more energy than the issue deserves."],
  ["Six", "adjustment, exchange, recognition, and movement toward a more workable balance", "Progress may be uneven, validation may be overvalued, or give-and-take may be out of proportion."],
  ["Seven", "testing, discernment, persistence, and the need to protect or evaluate what has been built", "Defensiveness, doubt, or poor strategy may be turning a useful test into unnecessary strain."],
  ["Eight", "focused movement, repetition, skill, and the consequences of sustained effort", "Speed, repetition, or effort may be continuing without enough reflection on whether the direction still makes sense."],
  ["Nine", "maturity, near-completion, self-reliance, and the final stretch before a cycle changes", "Weariness, guardedness, or fixation on self-sufficiency may be making support difficult to accept."],
  ["Ten", "culmination, consequence, responsibility, and the point where a cycle becomes too large to ignore", "The load may need to be redistributed, released, or understood differently before the next cycle can begin."],
  ["Page", "curiosity, messages, apprenticeship, and a beginner's willingness to engage", "Inexperience, mixed signals, or enthusiasm without follow-through may be creating noise."],
  ["Knight", "movement, pursuit, conviction, and the way an idea becomes behavior", "Momentum may be becoming haste, tunnel vision, or action without enough awareness of consequences."],
  ["Queen", "mature internal command, discernment, and the ability to embody the suit without proving it", "The suit's strengths may be turning inward as overcontrol, depletion, resentment, or self-protection."],
  ["King", "mature external command, responsibility, leadership, and stewardship of the suit's resources", "Authority may be becoming rigidity, ego, misuse of power, or an unwillingness to listen."],
] as const;

function slugify(value: string): string { return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""); }

function minorCards(): TarotCard[] {
  const cards: TarotCard[] = [];
  let id = 22;
  for (const [suitName, suit] of Object.entries(SUITS) as [Exclude<TarotSuit, null>, (typeof SUITS)[keyof typeof SUITS]][]) {
    for (const [rank, uprightPattern, reversedPattern] of RANKS) {
      const name = `${rank} of ${suitName}`;
      cards.push({
        id: id++, slug: slugify(name), name, arcana: "minor", suit: suitName, rank, glyph: suit.glyph,
        keywords: [rank.toLowerCase(), suitName.toLowerCase(), suit.theme.split(",")[0]],
        upright: `The ${name} brings ${uprightPattern} into the realm of ${suit.theme}.`,
        reversed: `Reversed, the ${name} suggests that ${reversedPattern.charAt(0).toLowerCase()}${reversedPattern.slice(1)} In this suit, pay special attention to ${suit.theme}.`,
        love: `In love and relationships, the ${name} highlights ${suit.love}; the ${rank.toLowerCase()} quality shows where that theme is currently developing.`,
        work: `In work and money, the ${name} focuses on ${suit.work}; approach the situation through the ${rank.toLowerCase()} lesson of the card rather than its surface drama.`,
        reflection: `How is the ${rank.toLowerCase()} lesson of ${suitName.toLowerCase()} showing up in your situation right now?`,
      });
    }
  }
  return cards;
}

export const TAROT_CARDS: TarotCard[] = [...MAJOR, ...minorCards()];
export const TAROT_BY_SLUG = new Map(TAROT_CARDS.map((card) => [card.slug, card]));
export function tarotBySlug(slug: string): TarotCard | undefined { return TAROT_BY_SLUG.get(slug.toLowerCase()); }
